- app/controllers/bulk_updates_controller.rb
- app/views/bulk_updates/index.html.erb
- app/views/bulk_updates/show.html.erb
- app/views/groups/show.html.erb
- app/views/layouts/manage_metadata.html.erb
- app/views/manage_metadata/show.html.erb
- config/routes.rb
- lib/cmr/cmr_client.rb
- lib/test_cmr/load_data.rb
- lib/test_cmr/test_data.json
- spec/controllers/bulk_updates_controller_spec.rb
- spec/features/bulk_updates/bulk_updates_list_spec.rb
- spec/features/bulk_updates/bulk_updates_search_spec.rb
- spec/features/bulk_updates/view_bulk_update_spec.rb
- spec/features/collections/delete_collection_spec.rb
- spec/features/collections/reverting_collection_spec.rb
- spec/features/search/quick_find_spec.rb
- spec/features/search/search_collections_result_spec.rb
- spec/features/search/search_form_spec.rb
> MMT-886: add ability to query endpoints and view bulk updates index and show pages

- app/views/manage_collections/show.html.erb
- app/views/manage_services/show.html.erb
- app/views/manage_variables/show.html.erb
- spec/features/collection_drafts/collection_draft_creation_spec.rb
Changed header boxes so they match wireframes "Create Collection Record" - "Create Variable Record".
> MMT-1033.1034: Changed text in header boxes 

- app/assets/stylesheets/components/_search.scss
- app/assets/stylesheets/layout/_header.scss
- app/views/layouts/application.html.erb
- app/views/shared/_user_info_dropdown.html.erb
-Added minor fix for IE11+ and Edge search dropdown
-Added major fixes for Safari search / user-info dropdown
-Added minor fix for Mozilla search dropdown button.
> MMT-1032: Hover fix

- app/controllers/application_controller.rb
- app/controllers/base_drafts_controller.rb
- app/controllers/collection_associations_controller.rb
- app/controllers/collection_drafts_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/manage_cmr_controller.rb
- app/controllers/manage_collections_controller.rb
- app/controllers/manage_metadata_controller.rb
- app/controllers/manage_variables_controller.rb
- app/controllers/variable_drafts_controller.rb
- app/controllers/variables_controller.rb
- app/helpers/variables_helper.rb
- app/policies/application_policy.rb
- app/policies/collection_draft_policy.rb
- app/policies/draft_policy.rb
- app/policies/provider_policy.rb
- app/policies/system_policy.rb
- app/policies/variable_draft_policy.rb
- app/views/collection_drafts/show.html.erb
- app/views/collections/show.html.erb
- app/views/drafts/show.html.erb
- app/views/variables/show.html.erb
- config/locales/en.yml
- spec/features/collection_drafts/collection_draft_permissions_spec.rb
- spec/features/variable_drafts/variable_draft_permissions_spec.rb
- spec/features/variables/variable_permissions_spec.rb
* add methods to ensure correct provider for variable manage collection associations actions
* refactor ensure correct provider methods for variables and collections
* convert ensuring correct provider for drafts to use Pundit policies
> MMT-1127: adds ensuring correct provider for variable manage collection associations

- app/assets/javascripts/change_current_provider.coffee
- app/assets/stylesheets/components/_action.scss
- app/controllers/collections_controller.rb
- app/controllers/variables_controller.rb
- app/helpers/variables_helper.rb
- app/models/variable_draft.rb
- app/views/collection_drafts/show.html.erb
- app/views/collections/show.html.erb
- app/views/drafts/show.html.erb
- app/views/shared/_not_current_provider_modal.html.erb
- app/views/variables/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/collection_drafts/auto_populate_metadata_dates_spec.rb
- spec/features/collection_drafts/collection_draft_deletion_spec.rb
- spec/features/collection_drafts/collection_draft_permissions_spec.rb
- spec/features/collection_drafts/create_collection_draft_from_cloning_collection_spec.rb
- spec/features/collection_drafts/create_collection_draft_from_collection_spec.rb
- spec/features/collection_drafts/create_collection_draft_from_dif10_collection_spec.rb
- spec/features/collection_drafts/publish_revision_with_non_url_encoded_native_id_spec.rb
- spec/features/collections/collection_permissions_spec.rb
- spec/features/collections/delete_collection_spec.rb
- spec/features/collections/reverting_collection_spec.rb
- spec/features/variable_drafts/create_variable_draft_from_cloning_variable_spec.rb
- spec/features/variable_drafts/variable_draft_deletion_spec.rb
- spec/features/variable_drafts/variable_draft_permissions_spec.rb
- spec/features/variables/variable_permissions_spec.rb
- spec/models/variable_draft_spec.rb
* add controller, model, and view changes for functionality to clone a Variable to create a Variable Draft, including tests
* add ensuring correct provider and changing provider functionality for cloning Varibles, including tests
* update action links css
* update action links wording for Collections and Collection Drafts, and tests that use the links
> MMT-1153: add cloning of published Variable to create a Variable Draft

- app/controllers/application_controller.rb
- app/controllers/collection_associations_controller.rb
- app/controllers/collection_drafts_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/drafts_controller.rb
- app/controllers/manage_cmr_controller.rb
- app/controllers/manage_metadata_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/variables_controller.rb
- spec/features/collections/delete_collection_spec.rb
- spec/features/variables/delete_variable_spec.rb
- implement method to display cmr error or I18n message or other default message.
> MMT-1146: ensure display of insufficient permissions message from CMR, if provided

- Gemfile
- Gemfile.lock
Updated one outdated gem. Pretty strait forward. Bamboo is green. Adding Jon V. since he was one of the people reporting this, just so that he sees progress.
> MMT-1505 - updating a gem file to make builds happy

- app/assets/stylesheets/layout/_header.scss
- app/helpers/collections_helper.rb
- app/views/collection_drafts/show.html.erb
- app/views/collections/revisions.html.erb
- app/views/collections/show.html.erb
- spec/factories/valid_collection_draft_factories.rb
- spec/features/collection_drafts/breadcrumbs_and_header_spec.rb
- spec/features/collections/breadcrumbs_and_header_spec.rb
- spec/support/draft_helpers.rb
When on the collection preview page. If the Collection Data Type is Near Real Time then the NRT badge displays next to the subtitle in the header section.
> MMT-1218 Collection Data Type Display

- config/schedule.rb
That should fix Bamboo build problem with Ruby path
> MMT-1491 fixed Bamboo build problem with Ruby path

- Gemfile.lock
updated an outdated gem. I just did a `bundle update nokogiri` and then committed the lock file.
> MMT-1520 - did a bundle update nokogiri and got this update

- app/controllers/base_manage_controller.rb
- app/controllers/base_published_record_controller.rb
- app/controllers/manage_metadata_controller.rb
- app/controllers/services_controller.rb
- app/controllers/variables_controller.rb
- app/helpers/manage_metadata_helper.rb
- app/views/manage_collections/show.html.erb
- app/views/manage_services/show.html.erb
- app/views/manage_variables/show.html.erb
Refactored VariablesController and ServicesController into a new controller called BaseManageController.
> MMT-1361 refactored two classes into one base class

- app/controllers/application_controller.rb
- app/controllers/saml_controller.rb
- app/controllers/users_controller.rb
- lib/cmr/client.rb
- spec/controllers/saml_controller_spec.rb
- spec/features/manage_cmr/provider_holdings_spec.rb
- spec/vcr/launchpad_status.yml
* fix test for launchpad
* add temporary logging upon launchpad login
> MMT-1551: keep alive and healthcheck point to correct launchpad environment

- app/assets/stylesheets/layout/_header.scss
- app/views/shared/_user_info_dropdown.html.erb
In specific instances the dropdown items would wrap around and display the items incorrectly.
> MMT-1375 prevent wrapping for dropdown items

- app/controllers/permissions_controller.rb
- spec/features/permissions/create_update_delete_permissions_spec.rb
- spec/fixtures/collection_permissions/failed_delete_acl_response.json
- spec/support/cmr_helper.rb
when delete collection permission without permission
> MMT-1374 Fix issue with display properly error message

- spec/features/permissions/create_update_delete_permissions_spec.rb
* CMR fixed issue preventing ingest when collection permission had access constraint values
> MMT-1516: uncomment access constraint values from collection permissions test

- Gemfile.lock
- spec/controllers/saml_controller_spec.rb
- spec/vcr/launchpad_status.yml
* updating nokogiri
* fixing launchpad test
> MMT-1592 - update of gem

- config/environments/development.rb
- config/environments/production.rb
- config/environments/sit.rb
- config/environments/uat.rb
adding settings to prevent X-Forward-Host manipulation
> MMT-1642 - X-Forward-Host

- app/assets/javascripts/variable_generation.coffee
- app/controllers/variable_generation_processes_controller.rb
- app/helpers/manage_metadata_helper.rb
- app/helpers/variable_generation_helper.rb
- app/views/variable_generation_processes/edit.html.erb
- app/views/variable_generation_processes/show.html.erb
- app/views/variable_generation_processes_searches/new.html.erb
- config/routes.rb
- doc/local_https_setup.md
- lib/cmr/client_middleware/event_middleware.rb
- lib/cmr/uvg_client.rb
- spec/controllers/variable_generation_processes_controller_spec.rb
- spec/features/variable_generation/naive_variable_generation_spec.rb
- spec/features/variable_generation/uvg_augmentation_spec.rb
* add augmentation selection and pages
* add calls to augmentation endpoints
* add controller actions and update views
* add and update tests
> MMT-1751: allow sending UVG augmentation request

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_variable_generation.scss
- app/controllers/variable_generation_processes_controller.rb
- app/helpers/variable_generation_helper.rb
- app/views/variable_generation_processes/show.html.erb
- config/environments/sit.rb
- config/routes.rb
- lib/cmr/base_client.rb
- lib/cmr/response.rb
- spec/features/variable_generation/uvg_saving_drafts_spec.rb
- spec/fixtures/variable_generation/full_stubbed_naive_response.json
- spec/fixtures/variable_generation/small_stubbed_naive_response.json
- spec/fixtures/variable_generation/zero_stubbed_naive_response.json
* add mass import gem
* add saving as variable drafts functionality utilizing mass import
* update buttons placement and style
* update helper methods
* attempt to resolve timeout issue
* add tests for saving drafts
> MMT-1752: add ability to save UVG generated variables as variable drafts

- app/controllers/variable_generation_processes_controller.rb
- app/helpers/variable_generation_helper.rb
- app/views/variable_generation_processes/_augment_keywords_statistics.html.erb
- app/views/variable_generation_processes/_generate_statistics.html.erb
- app/views/variable_generation_processes/show.html.erb
- lib/cmr/uvg_client.rb
- spec/controllers/variable_generation_processes_controller_spec.rb
- spec/features/variable_generation/naive_variable_generation_spec.rb
- spec/features/variable_generation/uvg_augmentation_spec.rb
- spec/features/variable_generation/uvg_saving_drafts_spec.rb
- spec/fixtures/variable_generation/full_stubbed_augment_keywords_response.json
- spec/fixtures/variable_generation/small_list_variables.json
- spec/fixtures/variable_generation/small_stubbed_naive_response.json
- spec/fixtures/variable_generation/zero_stubbed_naive_response.json
* allow augmentation request for science keywords
* display correct statistics
* update tests and stubs
* improve handling of save as drafts failure
> MMT-1743: allow UVG augmentation of science keywords request

- app/views/layouts/application.html.erb
- app/views/layouts/error.html.erb
- app/views/layouts/manage_cmr.html.erb
- app/views/layouts/manage_metadata.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/sit.rb
- config/environments/test.rb
- config/environments/uat.rb
Created a configuration for using SIT and UAT versions of TopHat in SIT and UAT
> MMT-1815 - adding Top Hat configuration

- app/assets/javascripts/orders.coffee
- app/controllers/orders_controller.rb
- app/views/orders/search.html.erb
- lib/echo/order.rb
- spec/features/orders/guest_orders_spec.rb
- spec/features/orders/listing_orders_spec.rb
- spec/features/orders/no_contact_orders_spec.rb
- spec/vcr/echo_soap/order_management_service/search_by_guid.yml
- spec/vcr/echo_soap/order_management_service/search_by_state_and_date.yml
* condense some columns, add guid and tracking id
* add sorting and filtering to order tracking table
* add tests
* fix owner username missing from table
> MMT-1204, MMT-1808: order tracking table improvements

- Gemfile.lock
- app/helpers/provider_identity_permissions_helper.rb
- app/helpers/system_identity_permissions_helper.rb
- spec/features/provider_identity_permissions/adding_provider_permissions_spec.rb
- spec/features/provider_identity_permissions/changing_removing_provider_permissions_spec.rb
- spec/features/provider_identity_permissions/provider_identity_permissions_form_spec.rb
- spec/features/system_identity_permissions/adding_system_permissions_spec.rb
- spec/features/system_identity_permissions/changing_removing_system_permissions_spec.rb
- spec/features/system_identity_permissions/system_identity_permissions_form_spec.rb
* address rubocop issues
* minor clean up
> MMT-1664: add Non-NASA Draft MMT User row to Provider Object ACLs table

- Gemfile
- MMT-1908: Updating preview gem to handle data centers with no short name
> MMT-1908 Updating preview gem commit ref

- Gemfile
- Gemfile.lock
Failed to commit with bundle install, so it could not deploy to SIT.
> Mmt 1908-2

- app/controllers/base_drafts_controller.rb
- app/controllers/collection_drafts_controller.rb
- app/controllers/manage_collections_controller.rb
- app/models/collection_draft.rb
- spec/features/collection_templates/template_create_draft_spec.rb
Also updated some logging to help differentiate what is being acted on.  
Changes to concurrency problems put off to a new ticket.
> Feature/mmt 38-2  Updating to cover 404 error when user submits no template id

- app/views/layouts/application.html.erb
- app/views/layouts/collection_preview.html.erb
- app/views/layouts/error.html.erb
- app/views/layouts/mailer.html.erb
- app/views/layouts/manage_cmr.html.erb
- app/views/layouts/manage_metadata.html.erb
Please review change to <html>  to add language tag.
> MMT-1832 added language attribute to html tag.

- Gemfile
- Gemfile.lock
> Feature/mmt 2042 - now uses latest preview gem

- app/controllers/collections_controller.rb
- app/controllers/proposal/collection_draft_proposals_controller.rb
- app/models/collection_draft_proposal.rb
- app/views/proposal/collections/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/proposal/collection_draft_proposals/collection_draft_proposal_create_from_collection_spec.rb
- spec/features/proposal/collection_draft_proposals/collection_draft_proposal_creation_spec.rb
- spec/features/proposal/collection_draft_proposals/collection_draft_proposal_update_spec.rb
- spec/models/collection_draft_proposal_spec.rb
* add link, modal, and controller actions for creating an update proposal
* move methods out of controller into model
* add tests
> MMT-1984: add ability to create a metadata update proposal

- app/controllers/collections_controller.rb
- app/controllers/manage_proposal_controller.rb
- app/controllers/proposal/collection_draft_proposals_controller.rb
- app/mailers/proposal_mailer.rb
- app/views/proposal_mailer/proposal_approved_notification.html.erb
- app/views/proposal_mailer/proposal_published_notification.html.erb
- app/views/proposal_mailer/proposal_published_notification.text.erb
- spec/features/manage_proposals/manage_proposal_publish_spec.rb
- spec/mailers/previews/proposal_mailer_preview.rb
- spec/mailers/proposal_mailer_spec.rb
Added mail to making a delete request.
Added mail to publishing a delete request
Added mail to publishing a create/update request
Updated approve/submit mails to accommodate update/delete requests
Fixed inconsistency in text for approve emails
Added tests for approve and publish email displays
> MMT-1717 adding mail to publishing proposals

- Dockerfile
- bashrc.env
- harbor.sh
Adding a docker file and a helper script called harbor.sh
> MMT-2057 - MMT in Docker

- app/assets/stylesheets/components/_masthead.scss
- app/views/layouts/application.html.erb
- app/views/layouts/collection_preview.html.erb
- app/views/layouts/error.html.erb
- app/views/layouts/manage_cmr.html.erb
- app/views/layouts/manage_metadata.html.erb
- app/views/welcome/index.html.erb
Removed 2nd main and .welcome css. Also added a separate header ender for each header element.
> MMT-1831 Fix Element Issues Flagged for 508 Compliance

- app/mailers/application_mailer.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/sit.rb
- config/environments/test.rb
- config/environments/uat.rb
- spec/mailers/draft_mailer_spec.rb
- spec/mailers/group_mailer_spec.rb
- spec/mailers/proposal_mailer_spec.rb
Updating MMT domain so that GMail should not filter it.
> MMT-2178 Updating default from address to prevent gmail filtering

- app/views/subscriptions/index.html.erb
- spec/features/manage_cmr/subscriptions/index_subscriptions_spec.rb
Updating create button visibility to be consistent with visibility constraints elsewhere
> MMT-2092 Updating create button on subscription page to be acl controlled.

- README.md
- lib/tasks/local_cmr.rake
adding a rake task to download the lattest CMR jar from the maven repository
> MMT-2197 - New Rake Task

- app/assets/javascripts/datetimepicker.coffee
- app/assets/javascripts/permissions.coffee
- app/assets/javascripts/required_fields.coffee
- app/controllers/manage_cmr/permissions_controller.rb
- app/controllers/manage_cmr/service_option_assignments_controller.rb
- app/helpers/permissions_helper.rb
- app/views/order_policies/_form.html.erb
- app/views/orders/_form.html.erb
- app/views/permissions/_form.html.erb
- spec/features/manage_cmr/permissions/create_update_delete_permissions_spec.rb
- spec/features/manage_cmr/permissions/permissions_form_spec.rb
- spec/features/manage_cmr/permissions/updating_permission_with_restricted_collections_spec.rb
- spec/features/manage_cmr/service_option_assignments/delete_service_option_assignments_spec.rb
* add temporal filter fields to collection permission form
* hook up datetime picker and radio buttons
* add validation of fields
* add or modify methods used for validation
* update helpers for show page explaining filters
* update tests to include new fields and validation
> MMT-2154: allow temporal filters for collection permissions

- Gemfile
- Gemfile.lock
- app/assets/javascripts/draft_form_selectors.coffee
- app/helpers/drafts_helper.rb
- app/views/collection_drafts/forms/fields/_horizontal_data_resolution_fields.html.erb
- config/application.rb
- lib/assets/schemas/collections/umm-c-json-schema.json
- lib/assets/schemas/collections/umm-c-merged.json
- spec/factories/collection_factory_data.rb
- spec/features/collection_drafts/forms/spatial_information_form_spec.rb
- spec/features/collection_previews/spatial_information_preview_spec.rb
Removed HorizontalResolutionProcessingLevelEnum from Point/Varies Resolution. Also added the 3 extra values to HorizontalDataResolutionUnitEnum: "Statute Miles", "Nautical Miles", and "Not provided".
> MMT-2205 Update to UMM-C 1.15.2

- lib/tasks/sloc.rake
add a rake command to run a sloc report. Plan for this to be executed in the future by a cron or some other trigger.
> MMT-2240 Rake task to run sloc report

- app/controllers/collections_controller.rb
- app/helpers/collections_helper.rb
- app/views/collections/show.html.erb
- app/views/proposal/collections/show.html.erb
- app/views/shared/_download_xml.html.erb
- lib/test_cmr/data/collection_57.yml
- lib/test_cmr/load_data.rb
- spec/features/collections/downloading_xml_spec.rb
- spec/features/proposal/search/collection_search_spec.rb
- spec/features/search/search_collections_result_spec.rb
- spec/features/services/list_collection_associations_spec.rb
Specified Native Format in Download Metadata Pop Up and fixed the ISO SMAP/MENDS formats
> MMT-2049 Specify Native Format in Download Metadata Pop Up and MMT-2268 for fixing the ISO formats

- app/views/manage_tools/show.html.erb
- config/routes.rb
- doc/local_https_setup.md
- spec/features/manage_tools/open_drafts_spec.rb
Adding the more link to view the index of tools
Will do a review Monday, 8th
> mmt-2222 - adding index view for Tools

- README.md
- app/assets/javascripts/search.coffee
- app/assets/stylesheets/components/_search.scss
- app/helpers/search_helper.rb
- app/views/shared/_search_form.html.erb
- spec/features/proposal/collection_draft_proposals/collection_draft_proposal_view_spec.rb
- spec/features/search/search_form_spec.rb
I managed to completely hose my MMT-2145 branch. Rather than trying to resurrect it, I created a new branch.  Here is the new pull request.
> MMT-2245 -- Remove option to search for variables and services in DMMT

- app/controllers/tools_controller.rb
- app/views/tools/show.html.erb
- config/routes.rb
- spec/features/collections/downloading_xml_spec.rb
- spec/features/tools/download_json_spec.rb
- spec/features/variables/download_json_spec.rb
adding download json for tools
> MMT-2234 Adding download json for tools

- app/assets/javascripts/change_current_provider.coffee
- app/controllers/tools_controller.rb
- app/views/shared/_not_current_provider_modal.html.erb
- app/views/tools/revisions.html.erb
- config/environments/production.rb
- config/environments/uat.rb
- config/locales/en.yml
- config/routes.rb
- spec/features/manage_cmr/subscriptions/delete_subscriptions_spec.rb
- spec/features/tools/reverting_tool_spec.rb
- spec/features/tools/revision_list_spec.rb
- spec/vcr/subscriptions/failed_delete.yml
Updating a subscriptions ticket that was causing intermittent failures.
> MMT-2232/2233 Revision viewing and reversion for tools

- app/assets/javascripts/change_current_provider.coffee
- app/controllers/collection_associations_controller.rb
- app/helpers/variables_helper.rb
- app/views/base_published_record/_manage_collection_associations.html.erb
- app/views/collection_associations/index.html.erb
- app/views/shared/_not_current_provider_modal.html.erb
- config/locales/en.yml
- spec/features/variables/create_collection_association_spec.rb
- spec/features/variables/delete_collection_assocation_spec.rb
- spec/features/variables/variable_permissions_spec.rb
Also added warnings for the cascade delete of variables in CMR.
> MMT-2329 Adjusting Variable-Collection associations to be singular in most places

- app/views/collections/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/sit.rb
- config/environments/test.rb
- config/environments/uat.rb
- spec/features/collections/loss_report_modal_spec.rb
- added feature toggle to be true for all non-prod environments
- added tests for this
> MMT-2388: Added loss-report toggle for all non-prod environments

- lib/tasks/local_cmr.rake
- package.json
- spec/features/proposal/deleting_old_proposals_spec.rb
Upgraded Coffeescript to 2.5.1 and Updated the local_cmr.rake file to use harmony flag
> MMT-2383 Upgraded Coffeescript to 2.5.1

- app/assets/javascripts/change_current_provider.coffee
- app/controllers/collection_associations_controller.rb
- app/helpers/manage_metadata_helper.rb
- app/views/shared/_not_current_provider_modal.html.erb
- app/views/tools/show.html.erb
- config/locales/en.yml
- config/routes.rb
- lib/cmr/cmr_client.rb
- spec/cmr/proposal_mode_removed_permissions/cmr_client_spec.rb
- spec/features/services/delete_collection_assocation_spec.rb
- spec/features/tools/create_collection_association_spec.rb
- spec/features/tools/delete_collection_assocation_spec.rb
- spec/features/tools/list_collection_associations_spec.rb
- spec/support/collection_association_helper.rb
Added manage associations link to published tool page.
Added correct underlining when looking at tool association pages.
Updated collection associations controller and change provider modal
Added associated routes
Updated cmr_client to share code for service/tool associations
Copied tests from service associations and updated for tools
> MMT-2416 Adding Collection-Tool Associations

- config/environments/sit.rb
> MMT-2410 update feature toggle

- app/assets/javascripts/accordion.coffee
- included the tag that surrounds the icon as the tag also opens the modal and click behavior needs to be handled for the tag as well
> hotfix/MMT-951-1: Francell change request

- .rspec
- Gemfile
- Gemfile.lock
- app/controllers/collections_controller.rb
- app/helpers/loss_report_helper.rb
- spec/features/collections/loss_report_spec.rb
Using an older version of mini_racer that doesn't require an updated GCC
> MMT-2463 update ruby version

- app/assets/stylesheets/base/_form.scss
- app/assets/stylesheets/components/_groups.scss
- app/views/permissions/_form.html.erb
- spec/features/manage_cmr/permissions/permissions_form_spec.rb
- Added support text hmtl
- wrote spec
> MMT-2466: Add Support Text in Collection Permissions UI to Notify Operators of S3 Bucket Access

- lib/cmr/util.rb
> MMT-2540: Update MMT and dMMT token handling to differentiate between new EDL token style and Launchpad tokens

- app/views/manage_collections/show.html.erb
- app/views/manage_services/show.html.erb
- app/views/manage_variables/show.html.erb
- app/views/shared/_provider_context.html.erb
- app/views/shared/_search_form.html.erb
- spec/features/collection_templates/template_create_draft_spec.rb
- added `title` attribute to each field that was lacking a `label` tag or `title` attribute
- adjusted spec
> MMT-2488:  SortSite Level A: MMT form has fields without LABEL elements or TITLE attributes

- app/assets/javascripts/related_urls.coffee
- app/helpers/drafts_helper.rb
- app/helpers/related_urls_helper.rb
- config/application.rb
- db/migrate/20210602183420_umm_c_1_16_2_to_1_16_3.rb
- db/schema.rb
- lib/assets/schemas/collections/umm-c-merged.json
- lib/assets/schemas/collections/umm-cmn-json-schema.json
* add new enums
* update helpers so enums show up
* update js for correct Related URL behavior with new Type enum
* write migration
> MMT-2555: update to UMM-C v 1.16.3 - add new enums for Related URL Type, Related URL Subtype, and URL Mime Type

- app/views/collection_drafts/forms/fields/_doi_fields.html.erb
- app/views/collection_drafts/forms/fields/_publication_reference_fields.html.erb
- db/migrate/20210610163713_fix_publication_doi_fields.rb
- db/schema.rb
- spec/migrations/fix_publication_doi_fields_spec.rb
- spec/support/draft_helpers.rb
- Changed form
- Wrote migration + migration tests
> MMT-2603: Collections->Data Identification->Publication References: Form validation error even though 'DOI Not Available' is selected and populated

- Gemfile
- Gemfile.lock
- app/assets/javascripts/draft_form_selectors.coffee
- app/assets/javascripts/validation.coffee
- app/controllers/collection_drafts_controller.rb
- app/views/collection_drafts/forms/fields/_geometry_fields.html.erb
- app/views/collection_drafts/forms/fields/_resolution_and_coordinate_system_fields.html.erb
- app/views/collection_drafts/forms/fields/_spatial_information_fields.html.erb
- app/views/collection_drafts/forms/fields/_use_constraints_fields.html.erb
- config/application.rb
- db/migrate/20211202173020_umm_c_1_16_5_to_1_16_6.rb
- db/schema.rb
- lib/assets/schemas/collections/umm-c-json-schema.json
- lib/assets/schemas/collections/umm-c-merged.json
- spec/factories/collection_factory_data.rb
- spec/features/collection_drafts/forms/data_identification_form_spec.rb
- spec/features/collection_drafts/forms/spatial_information_form_spec.rb
- spec/features/collection_drafts/forms/unselect_radio_buttons_spec.rb
- spec/features/collection_drafts/forms/validation_spec.rb
- spec/features/collection_previews/data_identification_preview_spec.rb
* copy and merge UMM-C v1.16.6
* add FreeAndOpenData field to UseConstraints fields
* modify UseConstraints type radio button selection and behavior
* modify clear radio button link data attrs and update function
* update validation for UseConstraints fields with oneOf and new field behavior
* update factory
* update tests
* add migration
> MMT-2710: update UMM-C to v1.16.6

- spec/features/bulk_updates/bulk_updates_data_centers_spec.rb
- spec/features/bulk_updates/bulk_updates_instruments_spec.rb
- spec/features/bulk_updates/bulk_updates_location_keywords_spec.rb
- spec/features/bulk_updates/bulk_updates_platforms_spec.rb
- spec/features/bulk_updates/bulk_updates_science_keywords_spec.rb
- spec/features/collection_templates/template_creation_spec.rb
MMT-2828 IS SUB-BRANCH FOR FIXING FIRST HALF FAILED TESTS FROM MMT-2792
> MMT-2828:FIXED FIRST HALF FAILED TESTS

- app/views/collection_drafts/forms/_data_identification.html.erb
- app/views/collection_drafts/forms/fields/_standard_product_fields.html.erb
If the user selected "false", the boolean radio button wasn't reflecting that, only for true.
> MMT-2845: Updated to show false in radio button for standard product.

- db/migrate/20220516145458_umm_c_1_16_7_to_1_17_0.rb
•	Rename Period to OrbitPeriod and use the enum
> Mmt 2925: Implement migration rules for Period and OrbitPeriod

- app/controllers/manage_cmr/groups_controller.rb
- app/controllers/manage_cmr/permissions_controller.rb
- app/helpers/groups_helper.rb
- app/views/groups/edit.html.erb
- app/views/groups/index.html.erb
- app/views/groups/show.html.erb
- app/views/provider_identity_permissions/index.html.erb
- app/views/shared/_not_current_provider_modal.html.erb
- app/views/system_identity_permissions/index.html.erb
- lib/cmr/urs_client.rb
- spec/features/manage_cmr/permissions/collection_permissions_list_spec.rb
- spec/features/manage_cmr/permissions/create_update_delete_permissions_spec.rb
- spec/features/manage_cmr/permissions/edit_permissions_with_invalid_revision_id_spec.rb
- spec/features/manage_cmr/permissions/permissions_form_spec.rb
- spec/features/manage_cmr/permissions/permissions_permissions_spec.rb
- spec/features/manage_cmr/permissions/updating_permission_with_restricted_collections_spec.rb
- spec/features/manage_cmr/permissions/updating_permission_with_system_groups_spec.rb
- spec/features/manage_cmr/permissions/viewing_permissions_spec.rb
- spec/fixtures/collection_permissions/get_cmr_groups_response.json
- spec/support/concept_helper.rb
Fixed group permissions in MMT
> MMT-2785: Using MMT to assign ACLs using EDL Groups

- spec/features/manage_cmr/permissions/updating_permission_with_restricted_collections_spec.rb
- spec/vcr/edl/updating_permission_with_restricted_collections_spec_admin_1_vcr.yml
- spec/vcr/edl/updating_permission_with_restricted_collections_spec_admin_submit_vcr.yml
- spec/vcr/edl/updating_permission_with_restricted_collections_spec_admin_vcr.yml
- spec/vcr/edl/updating_permission_with_restricted_collections_spec_some_vcr.yml
- spec/vcr/edl/updating_permission_with_restricted_collections_spec_submit_vcr.yml
- spec/vcr/edl/updating_permission_with_restricted_collections_spec_vcr.yml
> MMT-3057:Write "Manage CMR"->Permission and Chooser tests(Part 2)

- .env
- spec/features/variable_drafts/create_variable_draft_from_variable_spec.rb
- spec/features/variables/reverting_variable_spec.rb
Updated the access version number
> MMT-3073: When clicking on any of the preview page tabs at the top for download options (atom, Dif 10, etc.), they do not work in some cases.

- app/assets/javascripts/templates.coffee
- app/views/collection_drafts/show.html.erb
- app/views/drafts/index.html.erb
- app/views/manage_collections/show.html.erb
- spec/features/variable_drafts/create_variable_draft_from_variable_spec.rb
- spec/features/variables/reverting_variable_spec.rb
Added a spinner when a user uploads a collection draft and disable the Download JSON links after clicking.
> MMT-3068: As a user, see a spinner when uploading or downloading a collection draft

- app/javascript/components/editor/components/MetadataEditorForm.tsx
- app/javascript/components/editor/components/__tests__/__snapshots__/LayoutGridField.test.js.snap
- app/javascript/components/editor/components/widgets/CustomRadioWidget.tsx
- app/javascript/components/editor/components/widgets/Widget.css
- app/javascript/components/editor/components/widgets/__tests__/CustomRadioWidget.test.js
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomDateTimeWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomMultiSelectWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomRadioWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomSelectWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomTextWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomTextareaWidget.test.js.snap
- app/javascript/components/editor/data/configuration/uiSchemas/tools/potential_action.js
- app/javascript/components/editor/utils/json_utils.tsx
Ship the changes in Umm_tool_protype for Missing ‘Description’ field and ‘Value Required’ label on Tools->Potential Action->Query Input form
> MMT-3305:Missing ‘Description’ field and ‘Value Required’ label in UMM_TOOLS FORM

- app/javascript/components/editor/data/configuration/uiSchemas/tools/compatibility_and_usability.js
> MMT-3307: Use Constraints should not be a sub-field under Access Constraints (Tools React MMT)

- app/javascript/components/editor/components/__tests__/__snapshots__/MetadataEditorForm.test.js.snap
- app/javascript/components/editor/components/fields/__tests__/__snapshots__/LayoutGridField.test.js.snap
- app/javascript/components/editor/components/navigation/__tests__/__snapshots__/ErrorList.test.js.snap
- app/javascript/components/editor/components/templates/CustomArrayFieldTemplate.tsx
- app/javascript/components/editor/components/templates/CustomTitleFieldTemplate.tsx
- app/javascript/components/editor/components/templates/__tests__/CustomArrayTemplate.test.js
- app/javascript/components/editor/components/templates/__tests__/CustomTitleFieldTemplate.test.js
- app/javascript/components/editor/components/templates/__tests__/__snapshots__/CustomArrayTemplate.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomDateTimeWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomMultiSelectWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomSelectWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomTextWidget.test.js.snap
- app/javascript/components/editor/components/widgets/__tests__/__snapshots__/CustomTextareaWidget.test.js.snap
- app/javascript/components/editor/data/configuration/uiSchemas/services/service_options.js
> MMT-3354: - duplicate headers from Service Options

- static/src/css/vendor/bootstrap/overrides/_navbar.scss
- static/src/js/components/Page/Page.scss
- vite.config.js
This PR adds an alias to help loading static assets, which fixes an issue with loading background images from the Sass files.
> MMT-3436: Fixing loading of assets in scss files

- bin/deploy-bamboo.sh
- static.config.json
- static/src/js/components/PreviewMapTemplate/PreviewMapTemplate.jsx
- static/src/js/components/PreviewMapTemplate/__tests__/PreviewMapTemplate.test.js
Added a PreviewMapTemplet.jsx. Converted the PreviewMapLink.tsx from umm_tool_prototype to a functional component and added tests.
> MMT-3497: Convert the preview on map component to a functional component

- static/src/css/eui/_nested-item-picker.scss
- static/src/js/components/KeywordPicker/KeywordPicker.jsx
Added a spinner for the keyword picker
> MMT-3643: Keyword Picker has some styling issues where the widget isn’t initially positioned correctly.

- static/src/js/components/KeywordPicker/KeywordPicker.jsx
- static/src/js/pages/ManagePage/ManagePage.jsx
Fix the text under Create New Record button to reflect that concept type
> MMT-3602: Search text under "Create New Record" on the MMT homepage does not change regardless of the record type

- Gemfile
- Gemfile.lock
- package.json
- spec/features/chooser/chooser_disable_selected_options_spec.rb
- yarn.lock
Updates to packages used by Rails MMT.
Make necessary updates to react and rails packages used.
Updated jquery-ui-rails, moved some things to dev dependencies, and removed unnecessary packages.
MMT rails application.
See test session.
> MMT-3697: Updated jquery-ui-rails, other fixes.

- package-lock.json
- package.json
- serverless/src/getTemplate/__tests__/handler.test.js
- serverless/src/getTemplates/__tests__/handler.test.js
- serverless/src/updateTemplate/__tests__/handler.test.js
- static/src/js/components/AuthRequiredContainer/__tests__/AuthRequiredContainer.test.jsx
- static/src/js/components/EllipsisText/EllipsisText.jsx
- static/src/js/components/ErrorBoundary/__tests__/ErrorBoundary.test.jsx
- static/src/js/components/GroupForm/__tests__/GroupForm.test.jsx
- static/src/js/components/GroupList/GroupList.jsx
- static/src/js/components/GroupList/__tests__/GroupList.test.jsx
- static/src/js/components/GroupSearchForm/GroupSearchForm.jsx
- static/src/js/components/GroupSearchForm/__tests__/GroupSearchForm.test.jsx
- static/src/js/components/Header/Header.jsx
- static/src/js/operations/mutations/createGroup.js
- static/src/js/operations/mutations/updateGroup.js
- static/src/js/pages/GroupFormPage/__tests__/GroupFormPage.test.jsx
- static/src/js/pages/GroupListPage/GroupListPage.jsx
- static/src/js/pages/GroupListPage/__tests__/GroupListPage.test.jsx
- static/src/js/pages/GroupPage/GroupPage.jsx
- static/src/js/pages/GroupPage/__tests__/GroupPage.test.jsx
- static/src/js/pages/OrderOptionPage/__tests__/OrderOptionPage.test.jsx
- static/src/js/schemas/groupSearch.js
- static/src/js/schemas/uiSchemas/GroupSearch.js
- static/src/js/utils/__tests__/constructDownloadableFile.test.js
- test-setup.js
- vite.config.js
Adds a search form to the Groups list page
Searching for Groups
Visit the groups page, search for groups by name/provider/members
> MMT-3538: Adds search form to Groups list

- setup/setupCmr.js
- static/src/js/App.jsx
- static/src/js/components/Providers/Providers.jsx
- static/src/js/components/Providers/__tests__/Providers.test.jsx
- static/src/js/pages/ProvidersPage/ProvidersPage.jsx
- static/src/js/pages/ProvidersPage/__tests__/ProvidersPage.test.jsx
- static/src/js/schemas/uiSchemas/collections/spatialInformation.jsx
Adds a providers page to show the user their list of available providers
New `/providers` page
Got to `/providers`, view list of providers
> MMT-3740: Adds providers page

- static/src/js/components/SystemPermissions/__tests__/SystemPermissions.test.jsx
- static/src/js/providers/GraphQLProvider/GraphQLProvider.jsx
There was a caching related bug resulting in checkboxes showing up incorrectly, that has now been fixed.
> MMT-3681: Fixes a bug associated with ACL Group caching

- bin/deploy-bamboo.sh
- serverless.yml
- serverless/src/samlCallback/__tests__/handler.test.js
- serverless/src/samlCallback/handler.js
- static.config.json
- static/src/js/hooks/useMMTCookie.js
- static/src/js/providers/AuthContextProvider/AuthContextProvider.jsx
- static/src/js/providers/AuthContextProvider/__tests__/AuthContextProvider.test.jsx
Fixes a bug where logout didn't work in Safari or Firefox
Logging out
Using Safari and Firefox, login then ... logout
> MMT-3631: Fixes logging out in safari and firefox

- static/src/js/App.jsx
- static/src/js/components/Button/Button.jsx
- static/src/js/components/KeywordRecommendations/__tests__/KeywordRecommendations.test.jsx
- static/src/js/components/Layout/Layout.jsx
- static/src/js/components/Layout/__tests__/Layout.test.jsx
- static/src/js/components/Permission/Permission.jsx
- static/src/js/components/Permission/__tests__/Permission.test.jsx
- static/src/js/components/PrimaryNavigation/PrimaryNavigation.jsx
- static/src/js/pages/DraftListPage/__tests__/DraftListPage.test.jsx
- static/src/js/pages/HomePage/HomePage.jsx
- static/src/js/pages/LogoutPage/LogoutPage.jsx
- static/src/js/pages/LogoutPage/__tests__/LogoutPage.test.jsx
- static/src/js/pages/SearchPage/SearchPage.jsx
- static/src/js/providers/AuthContextProvider/AuthContextProvider.jsx
- static/src/js/providers/AuthContextProvider/__tests__/AuthContextProvider.test.jsx
Fixes issue with logout by using react router Link instead of href.
Fixes prop type errors
Logging out
Login then ... logout
> MMT-3739: Fixes logout issue

- static/src/js/components/TemplateList/TemplateList.jsx
- static/src/js/components/TemplateList/__tests__/TemplateList.test.jsx
Deleting from the template list was using app context provider id, and it needs to use the selected template's provider id
TemplateList
Delete a template from the TemplateList component
> MMT-3778: Fixes deleting from template list

- static/src/js/components/GridCheckboxPanel/GridCheckboxPanel.jsx
- static/src/js/components/GridControlledField/GridControlledField.jsx
- static/src/js/components/GridControlledField/__tests__/GridControlledField.test.jsx
- static/src/js/components/GridRow/GridRow.jsx
- static/src/js/components/TemplateForm/TemplateForm.jsx
- static/src/js/components/TemplateForm/__tests__/TemplateForm.test.jsx
- static/src/js/components/TemplatePreview/TemplatePreview.jsx
- static/src/js/utils/__tests__/handleShortNameChange.test.js
- static/src/js/utils/handleShortNameChange.js
Fixes various bugs found when testing templates in SIT
Templates
> MMT-3778: Fixes template bugs

- static/src/js/components/AssociatedCollectionPermissionsTable/AssociatedCollectionPermissionsTable.jsx
- static/src/js/components/AssociatedCollectionPermissionsTable/__tests__/AssociatedCollectionPermissionsTable.test.jsx
- static/src/js/components/CollectionSelector/CollectionSelector.jsx
- static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx
- static/src/js/components/CustomCheckboxWidget/CustomCheckboxWidget.jsx
- static/src/js/components/Group/Group.jsx
- static/src/js/components/Group/__tests__/Group.test.jsx
- static/src/js/components/GroupPermissionSelect/GroupPermissionSelect.jsx
- static/src/js/components/Permission/Permission.jsx
- static/src/js/operations/queries/getGroupAcls.js
- static/src/js/pages/GroupPage/__tests__/GroupPage.test.jsx
- static/src/js/schemas/uiSchemas/collectionPermission.js
During SIT testing there were some css and functionality issues found in collection permission form:
1) The All Collections page table overlaps with the section below. ✅ 
2) When clicking on the Group, should the Associated Collection Permissions say TBD. ✅ 
3)When editing a collection permission there is some style issues in safari ✅ 
4) The options under Search, Order, and S3 (If Available) should probably have a fixed height ✅ 
5) When I was trying to select a few collections, the Select Collection widget, the UI blanked out on me, but eventually came back ✅ 
6) The tooltip for the trash icon should probably say "Remove all" or "Clear Selections" instead of trash ✅ 
7) If I press enter in Search Collections (with nothing in the search box), I see the error below, like it is trying to …
> MMT-3776: Issues found testing collection permissions

- static/src/js/schemas/uiSchemas/collections/spatialInformation.jsx
Added a `ui:widget: 'textbox'` for the description field for Resolution and Coordinate System
> MMT-3650: Resolution and Coordinate System -> Description should be a text area (char length is 2048 chars)

- bin/deploy-bamboo.sh
- index.html
- package-lock.json
- package.json
- serverless.yml
- static.config.json
- static/src/js/schemas/uiSchemas/collections/collectionInformation.js
- vite.config.js
Add GA4 to React MMT
Add GA4 code to the index page
Index page
GA4 team will check MMT events sent to GA4 
N/A
> MMT-3771: Add Google Analytics 4 code

- bin/deploy-bamboo.sh
- bin/download_schemas.sh
- static.config.json
- static/src/js/schemas/umm/ummCSchema.js
- static/src/js/schemas/umm/ummSSchema.js
- static/src/js/schemas/umm/ummTSchema.js
- static/src/js/schemas/umm/ummVarSchema.js
Download and process umm schema files at deployment
Create script called by deployment script
All umm schema files
Test all forms of all available types: C, S, Var and T
N/A
> MMT-3793: Add script to download umm schema files at deployment

- bin/deploy-bamboo.sh
- bin/download_schemas.sh
Fix file paths
File path fixed
Bamboo deployment
Bamboo deployment should run successfully
N/A
> MMT-3793: Fix file paths for download script

- Gemfile.lock
Security fixes.
Update rexml
Packages used by MMT.
Brief regression testing would be beneficial to make sure nothing breaks.
> MMT-3868: Updated rexml

- package-lock.json
Security fixes.
Update axios and elliptic.   Still no upgrade path for fast-xml-parser
Packages used by MMT
Brief regression testing would be beneficial to make sure nothing breaks.
> MMT-3873: Updated axios and elliptic

- package-lock.json
Vulnerability fixes.
`npm audit fix`
MMT package updates.
See Jira ticket.
> MMT-3930: Vulnerabilities fix.

- bin/download_schemas.sh
Schema download script has test variable assignment
Remove test variable
Download schema in deployment
Run bin/download_schemas.sh with variable $bamboo_STAGE_NAME set (sit, uat or prod)
N/A
> MMT-3876: Remove test value assignment

- package-lock.json
MMT React Vulnerabilities November 2024
run 'npm audit fix'
Vulnerabilities in:
cross-spawn  <6.0.6 || >=7.0.0 <7.0.5
Severity: high
elliptic  <6.6.0
jsonpath-plus  <10.0.7
Severity: critical
See ticket's test session
N/A
> MMT-3948: Fix Vulnerabilities November 2024

- package-lock.json
- static/src/js/schemas/umm/ummVarSchema.js
There was a recent change to CMR to support updating the character limit for the Code System Identifier Meaning field in UMM-Var; see the details of the change in https://bugs.earthdata.nasa.gov/browse/CMR-9878. 
This change is needed in MMT as well since this change was requested by LP DAAC and they use MMT to curate their variable metadata. LP DAAC needs this fix to support their efforts for Web Unification.
Note: LP DAAC needs this fix before Web Unification. If this ticket isn't completed in 24.3 or at the latest in 24.4, Web Unification will be impacted. 
Changed maxLength of CodeSystemIdentifierMeaning to 1024 from 60. MinLength was already at 1. 
I also ran an npm audit fix to address critical issues.
ummVarSchema
- **Environment for testing: UAT
- **Collection to test with: …
> MMT-3968: Update MMT To Support UMM-Var Version 1.9 (CodeSystemIdentifierMeaning Length)

- package-lock.json
- package.json
Updates metadata preview library
> ECHOACCESS-251: Updates metadata preview library

- package-lock.json
- package.json
- static/src/js/components/KeywordTree/KeywordTree.jsx
- static/src/js/components/KeywordTree/KeywordTree.scss
- static/src/js/components/KeywordTree/__tests__/KeywordTree.test.jsx
- static/src/js/components/KeywordTreeContextMenu/KeywordTreeContextMenu.jsx
- static/src/js/components/KeywordTreeContextMenu/KeywordTreeContextMenu.scss
- static/src/js/components/KeywordTreeContextMenu/__tests__/KeywordTreeContextMenu.test.jsx
- static/src/js/components/KeywordTreeCustomNode/KeywordTreeCustomNode.jsx
- static/src/js/components/KeywordTreeCustomNode/KeywordTreeCustomNode.scss
- static/src/js/components/KeywordTreeCustomNode/__tests__/KeywordTreeCustomNode.test.jsx
- static/src/js/components/KeywordTreePlaceHolder/KeywordTreePlaceHolder.jsx
- static/src/js/components/KeywordTreePlaceHolder/KeywordTreePlaceHolder.scss
- static/src/js/components/KeywordTreePlaceHolder/__tests__/KeywordTreePlaceHolder.test.jsx
- static/src/js/components/KmsConceptSchemeSelector/__tests__/KmsConceptSchemeSelector.test.jsx
- static/src/js/pages/KeywordManagerPage/KeywordManagerPage.jsx
- static/src/js/pages/KeywordManagerPage/KeywordManagerPage.scss
- static/src/js/pages/KeywordManagerPage/__tests__/KeywordManagerPage.test.jsx
- static/src/js/utils/__tests__/getKmsKeywordTree.test.js
- static/src/js/utils/getKmsKeywordTree.js
Keyword tree to display keywords
Add a keyword tree
Keyword tree in Keyword Manager
Browse the tree and select a keyword to edit.
N/A
> MMT-4009: Add Keyword Tree to Keyword Manager

- static/src/js/schemas/uiSchemas/visualizations/index.js
- static/src/js/schemas/uiSchemas/visualizations/temporalExtents.js
Users can edit Temporal Extent
Added Temporal Extent to forms
Temporal Extent for the umm-vis forms
- **Environment for testing: any
- **Collection to test with: any
1. Create a draft with temporal extents. Make sure the form renders all appropriate fields and they work as expected
> MMT-3997: As a user, I can edit the Temporal Extent

- static.config.json
- static/src/js/components/Layout/Layout.jsx
- static/src/js/constants/conceptIdTypes.js
- static/src/js/constants/conceptTypeDraftQueries.js
- static/src/js/constants/conceptTypeQueries.js
- static/src/js/constants/deleteMutationTypes.js
- static/src/js/operations/mutations/deleteCitation.js
- static/src/js/operations/queries/getCitation.js
- static/src/js/operations/queries/getCitationDraft.js
- static/src/js/providers/GraphQLProvider/GraphQLProvider.jsx
- static/src/js/schemas/otherSchemasCitSchema.js
- static/src/js/schemas/uiForms/citationConfiguration.js
- static/src/js/schemas/uiForms/index.js
- static/src/js/utils/__tests__/getConceptTypeByConcept.test.js
- static/src/js/utils/__tests__/getUmmSchema.test.js
- static/src/js/utils/getConceptTypeByConceptId.js
- static/src/js/utils/getUmmSchema.js
Allow selection of individual citations or citation drafts in MMT
Added code to allow for selection of individual citations or citation drafts in MMT
React MMT Citations
Look for a citation and a citation draft in the cmr environment you are working in. If none exist you may have to ingest them.
Login to MMT.
Navigate to Citations/All Citations. Click on a Citation Short Name.
Make sure the page for the individual citation shows up.
Repeat for Drafts under Citations.
Make sure the page for the individual draft shows up.
Note: the name may come up as <Blank name>
> MMT-4056: Allowing selection of individual citation or citation draft

- bin/start-env.js
- package-lock.json
- package.json
- static/src/js/pages/SearchList/SearchList.jsx
- static/src/js/pages/SearchList/__tests__/__mocks__/searchResults.js
- static/src/js/pages/SearchPage/SearchPage.jsx
- static/src/js/pages/SearchPage/__tests__/SearchPage.test.jsx
Users can search by keyword for visualization records
Users can search by keyword for citation records
I also added a new start script for when devs need to start the app in a sit or uat environment. Do run it enter $ npm run start:app-env <edl password>
Add Search bar back into All Citations and All Visualizations
SearchList and SearchPage
- **Environment for testing:SIT
You will need cmr-graphql pointed to GQL-128 for this to work
1. Go to All Visualizations and in the search bar, search for 'rock'. One record should show up. Please note that only recently added visualizations are ready to be indexed by the keyword search functionality. So searching for previously made records may not produce the items you are looking for. You can create a new …
> MMT-4023: Add Search to All Visualizations and All Citations
