nasa/mmt

Gemfile, Gemfile.lock, app/concerns/chooser_endpoints.rb, app/controllers/manage_cmr_controller.rb
On certain endpoints the paths were pretty long, this was being written to the session for the purposes of redirecting after login, but a user will never visit these pages which means we can skip the filter that sets it. The filter also ensures that the user is logged in but the ajax request wont fire because the page itself WILL run through that before filter.
A user could hit the endpoint directly but will get nothing back because it requires a token that is retrieved and stored for logged in user, so there is no risk here.
=> MMT-637: Prevent writing the return_to path to the session for ajax endpoints

app/concerns/bulk_updates.rb, app/controllers/bulk_updates_controller.rb, app/controllers/manage_metadata_controller.rb, app/views/manage_metadata/show.html.erb, lib/test_cmr/test_data.json, spec/controllers/bulk_updates_controller_spec.rb, spec/controllers/manage_metadata_controller_spec.rb, spec/features/manage_metadata/bulk_updates_list_spec.rb, spec/features/manage_metadata/open_drafts_spec.rb
- add bulk updates listings to callout box on Manage Metadata 'dashboard'
- move getting bulk updates list to a concern to use in manage_metadata and bulk_updates controllers
- add controller test
- add feature test, and move drafts listing test to manage_metadata folder
=> MMT-875: Add bulk updates listings to Manage Metadata 'dashboard'

lib/test_cmr/load_data.rb, lib/test_cmr/test_data.json
Updates collections used in test data:
- update collection ingested and used for non-ASCII characters spec
- lightly edit test data file
- lightly refactor script that ingests test data
=> MMT-938: Fix broken test of non-ASCII characters

app/assets/javascripts/permissions.coffee, app/assets/stylesheets/components/_tables.scss, app/concerns/chooser_endpoints.rb, app/controllers/manage_cmr_controller.rb, app/controllers/permissions_controller.rb, app/helpers/application_helper.rb, app/helpers/permissions_helper.rb, app/views/permissions/_form.html.erb, app/views/permissions/edit.html.erb, app/views/permissions/index.html.erb, app/views/permissions/show.html.erb, config/routes.rb, lib/cmr/cmr_client.rb, lib/test_cmr/load_data.rb, spec/controllers/permissions_controller_spec.rb, spec/features/groups/group_list_permission_spec.rb, spec/features/permissions/collection_permissions_list_spec.rb, spec/features/permissions/create_update_delete_permissions_spec.rb, spec/features/permissions/permissions_form_spec.rb, spec/features/permissions/updating_permission_with_restricted_collections_spec.rb, spec/features/permissions/updating_permission_with_system_groups_spec.rb, spec/features/permissions/viewing_permissions_spec.rb, spec/features/service_entries/update_service_entry_spec.rb, spec/support/cmr_helper.rb, spec/support/controller_helpers.rb, spec/support/group_helper.rb
MMT-837: Updates the display of collections to an easier to read,
sortable table format.
MMT-940: Allow access constraint min and max to be equal
MMT-941: Allow for display and saving of granule only permissions
MMT-942: Removes Permission Type from the permissions index page
=> MMT-837, MMT-940, MMT-941, MMT-942: Collection Permission Updates

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_navigation.scss, app/controllers/collections_controller.rb, app/controllers/drafts_controller.rb, app/controllers/search_controller.rb, app/helpers/manage_metadata_helper.rb, app/helpers/users_helper.rb, app/views/collections/revisions.html.erb, app/views/collections/show.html.erb, app/views/drafts/edit.html.erb, app/views/drafts/index.html.erb, app/views/drafts/show.html.erb, app/views/groups/index.html.erb, app/views/groups/show.html.erb, app/views/layouts/application.html.erb, app/views/layouts/manage_metadata.html.erb, app/views/search/_collection_search_results.html.erb, app/views/search/index.html.erb, app/views/shared/preview/_collection_details.html.erb, spec/features/collections/collection_permissions_spec.rb, spec/features/collections/collection_with_draft_spec.rb, spec/features/drafts/create_draft_from_cloning_collection_spec.rb, spec/features/drafts/draft_creation_spec.rb, spec/features/drafts/draft_permissions_spec.rb, spec/features/drafts/forms/number_fields_spec.rb, spec/features/drafts/publish_draft_spec.rb, spec/features/manage_metadata/open_drafts_spec.rb, spec/features/search/search_drafts_result_permissions_spec.rb, spec/features/search/view_search_results_spec.rb
- controllers use header inherited from manage_metadata layout including breadcrumbs
- views for drafts and collections use breadcrumbs consistent with the rest of the app
- views that use the cmr_metadata_preview gem don't use the header partial from the gem and move any necessary portions back into MMT
- minor modifications of nav menus on the show/preview pages of drafts and collections
- fix tests to align with header changes
=> MMT-948: have Collections and Drafts Controllers inherit from ManageMetadataController

Gemfile, Gemfile.lock, app/controllers/saml_controller.rb, app/models/account.rb, app/views/saml/failure.html.erb, config/routes.rb
- Add SamlController, Account model, and routes for the SAML endpoints
- does not run the controller methods, but allows the routes to be checked by launchpad
=> MMT-1286 SAML Base

doc/local_cmr_documentation.md, lib/tasks/acls.rake, lib/test_cmr/load_data.rb, lib/test_cmr/test_data.json, spec/features/collections/empty_response_when_setting_collection_spec.rb, spec/features/groups/group_list_permission_spec.rb, spec/features/groups/groups_list_spec.rb, spec/features/permissions/collection_permissions_list_spec.rb, spec/features/permissions/create_update_delete_permissions_spec.rb, spec/features/permissions/updating_permission_with_restricted_collections_spec.rb, spec/features/permissions/updating_permission_with_system_groups_spec.rb, spec/features/provider_identity_permissions/provider_identity_permissions_form_spec.rb, spec/features/system_identity_permissions/system_identity_permissions_form_spec.rb, spec/rails_helper.rb, spec/support/concept_helper.rb, spec/support/group_helper.rb, spec/support/user_helpers.rb
* adjust calls in cmr startup script file
* add more comments
* change the way concept ids are used in ACLs
* modify tests and helpers
* modify the way concept ids are used in some tests
* add draft readme for local cmr setup
* add comments in acl rake tasks file
=> MMT-1467: revise local cmr setup to create ACLs in CMR Access Control instead of Mock Echo.

app/views/collection_drafts/forms/_data_identification.html.erb
This change should remove the link from the sub fields under Processing Level. The branch name is not of the ticket number on advice from Jon on how to process patches in Bamboo.
=> MMT-1477 added description link to top level field 'Processing Level'

app/middleware/middleware_healthcheck.rb
and rescue from more exceptions
=> MMT-1581: allow /status call to Launchpad /heathcheck to fail gracefully

Gemfile.lock
This version of loofah is safer
=> MMT-1605 - updating the Loofah GEM

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/controllers/welcome_controller.rb, lib/cmr/base_client.rb, lib/cmr/cmr_client.rb, lib/cmr/response.rb, lib/cmr/util.rb, spec/cmr/client_spec.rb, spec/factories/user.rb, spec/features/groups/groups_list_spec.rb, spec/features/provider_context/provider_context_spec.rb, spec/features/users/user_login_spec.rb, spec/support/cmr_helper.rb, spec/support/user_helpers.rb
* add logging for URS login and refresh token
* add and update tests
* add server session time check to redirect_if_logged_in
MMT-1446: remove use of echo_id
=> MMT-1594: redirect user to log in if refresh_token fails.

Gemfile, Gemfile.lock
CMR made a change, related to FTP, this merge is simply moving up to the version they committed.
=> pulling in the most recent preview change from the most recent CMR change

Gemfile, Gemfile.lock
web driver is EOL, switching to chrome driver helper as this is the recommended migration path
=> MMT-1820 - Switching from 'web drivers' as 'chrome driver helper'

app/assets/javascripts/drafts.coffee, app/helpers/form_helper.rb, app/views/collection_drafts/forms/fields/_get_service_fields.html.erb, config/routes.rb, lib/assets/schemas/services/umm-s-form.json, lib/json_schema_form/umm_form.rb, spec/features/service_drafts/service_draft_creation_spec.rb
Caught an error in last the last iteration where closed accordion bodies were being wiped out before submission too.  Investigated "is-invisible", but did not find use cases in the current draft forms.  Fixed spec test and added one for the closed accordion body case.
=> MMT 1819 - Preventing Submission of Hidden Fields

app/assets/stylesheets/components/_callout-box.scss, app/views/manage_collections/show.html.erb, app/views/manage_services/show.html.erb, app/views/manage_variables/show.html.erb
Hid short and long names that were overflowing their callout boxes and added tooltips to display short and long names on mouseover.  No tests were added.  Additionally, fixed color mismatch on variables generation callout box.
=> MMT 1525 - Tooltips for long short and long names on manage X screens

README.md, lib/cmr/launchpad_client.rb
* Updated the URL for the keep alive API
* Updated readme to add tip on how to install a gem
=> Use latest API URL for launch pad

app/assets/javascripts/data_management.coffee, app/assets/javascripts/order_option_assignments.coffee, app/assets/javascripts/permissions.coffee, app/assets/javascripts/service_management.coffee, app/assets/javascripts/widgets/Chooser/Chooser.coffee, app/controllers/data_quality_summary_assignments_controller.rb, app/views/permissions/_form.html.erb, spec/features/chooser/chooser_expected_behavior_spec.rb, spec/features/order_option_assignments/create_order_option_assignments_spec.rb, spec/features/order_option_assignments/delete_order_option_assignments_spec.rb, spec/features/permissions/create_update_delete_permissions_spec.rb, spec/features/permissions/permissions_form_spec.rb, spec/features/service_entries/update_service_entry_spec.rb, spec/features/service_option_assignments/create_service_option_assignments_spec.rb
Updated tooltip text.
Using a + or - button no longer automatically selects something from the right side.
Pressing enter no longer clicks the + button.
Selecting the right filter box clears selections from the right list of entries.  This removes the possibility of a user using the - button to remove an entry they could no longer see.
=> Mmt-1886 Updating chooser widgets to remove some unexpected behaviors

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_metadata-preview.scss, app/controllers/proposal/collection_draft_proposals_controller.rb, app/mailers/proposal_mailer.rb, app/models/collection_draft_proposal.rb, app/policies/collection_draft_proposal_policy.rb, app/views/proposal/collection_draft_proposals/show.html.erb, app/views/proposal_mailer/proposal_submitted_notification.html.erb, app/views/proposal_mailer/proposal_submitted_notification.text.erb, config/locales/en.yml, config/routes.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_destroy_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_submit_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_update_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_view_spec.rb, spec/mailers/draft_mailer_spec.rb, spec/mailers/group_mailer_spec.rb, spec/mailers/previews/proposal_mailer_preview.rb, spec/mailers/proposal_mailer_spec.rb, vendor/assets/stylesheets/eui-1.1.7/eui.css
Making the rescind button was much faster than making new records to test submit and its side effects.  The rescind button is the work for MMT-1981, so this PR satisfies both tickets.
- Added a guard in proposal's edit such that only proposals 'in work' can be edited.  
- Added submit and rescind actions to controller.
- Added mailer for submitting a proposal
- Added submitted state, submit and rescind events in model
- Added submit and rescind policies (same as update)
- Updated submit button to correct link and added rescind button in 'Submitted' state
- Updated show view to not display progress when draft is submitted
- Tests
- Routes
=> MMT-1980 MMT-1981 Adding submit button and rescind buttons to dMMT workflow.

Gemfile.lock, app/controllers/proposal/collection_draft_proposals_controller.rb, spec/features/proposal/proposal_progress_spec.rb
Writing the default_with_time_zone was causing it to throw an error while parsing it on retrieval.  The test case provided here actually invokes the add_status_history call rather than using the helper methods, so automated testing should catch this mistake from here on.
=> MMT-1993 Formatting the timestamp on retrieval, not writing to allow proper retrieval

Gemfile.lock, app/assets/stylesheets/components/_metadata-preview.scss, app/concerns/permission_checking.rb, app/controllers/collections_controller.rb, app/controllers/proposal/collection_draft_proposals_controller.rb, app/controllers/search_controller.rb, app/helpers/manage_metadata_helper.rb, app/helpers/proposals_helper.rb, app/models/collection_draft_proposal.rb, app/views/proposal/collection_draft_proposals/progress.html.erb, app/views/proposal/collection_draft_proposals/show.html.erb, app/views/proposal/collections/show.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/invalid_collection_draft_proposal_factories.rb, spec/factories/valid_collection_draft_proposal_factories.rb, spec/features/proposal/access_permissions/no_permissions_for_draft_mmt_spec.rb, spec/features/proposal/access_permissions/permissions_for_non_nasa_draft_approver_spec.rb, spec/features/proposal/access_permissions/permissions_for_non_nasa_draft_user_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_creation_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_submit_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_update_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_view_spec.rb, spec/features/proposal/proposal_progress_spec.rb
Added the ability to create and rescind a delete metadata proposal request.  Updated the look of the badges per PO feedback (to include the request type).  Updated permissions for search/collections pages in dMMT.
=> MMT-1989 Create a delete metadata proposal request

app/models/collection_draft_proposal.rb, db/migrate/20191105200412_add_required_to_proposal_status.rb, db/schema.rb, spec/models/collection_draft_proposal_spec.rb
AASM does an incomplete job of masking nils.  For most cases, it reports nil as 'in work' and can function, but Charles noticed that it does not work with operations that are closer to the database, e.g. where(proposal_status = 'in_work').  This sort of query is used in the approver views.
=> MMT-1966 updating the table to require a proposal_status

app/controllers/manage_proposal_controller.rb, app/controllers/proposal/approved_proposals_controller.rb, app/models/collection_draft_proposal.rb, config/locales/en.yml, config/routes.rb, lib/cmr/dmmt_client.rb, lib/tasks/bamboo.rake, spec/features/manage_proposals/approver_workflow_spec.rb, spec/features/manage_proposals/manage_proposal_publish_spec.rb, spec/models/collection_draft_proposal_spec.rb, spec/support/approved_proposals_helpers.rb
Added calls in publish proposal to update proposal status in dMMT.
Added endpoint to dMMT to update proposal status.
Refactored the endpoint in dMMT to get approved proposals to reuse the token validation section
Added AASM transition to 'done'.
Added helpers in tests to mock a call to URS and dMMT.
=> MMT-1962 Added the ability for MMT to update proposal statuses in dMMT.

app/assets/stylesheets/components/_metadata-preview.scss, app/assets/stylesheets/components/_timeline.scss, app/concerns/permission_checking.rb, app/controllers/application_controller.rb, app/controllers/manage_proposal_controller.rb, app/controllers/proposal/collection_draft_proposals_controller.rb, app/controllers/proposal/manage_collection_proposals_controller.rb, app/helpers/proposals_helper.rb, app/views/manage_proposal/show.html.erb, app/views/proposal/collection_draft_proposals/index.html.erb, app/views/proposal/collection_draft_proposals/progress.html.erb, app/views/proposal/collection_draft_proposals/proposal_partials/_delete_modal.html.erb, app/views/proposal/collection_draft_proposals/proposal_partials/_rescind_modal.html.erb, app/views/proposal/collection_draft_proposals/show.html.erb, app/views/proposal/collections/show.html.erb, app/views/proposal/manage_collection_proposals/show.html.erb, app/views/shared/_user_info_dropdown.html.erb, config/locales/en.yml, spec/features/manage_proposals/approver_workflow_spec.rb, spec/features/manage_proposals/manage_proposal_publish_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_create_from_collection_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_list_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_submit_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_update_spec.rb, spec/features/proposal/proposal_progress_spec.rb
Did a find and replace for the CSS on the progress page: timeline-faded-node => timeline-node-faded for consistency with other classes.  Similarly for timeline-faded-line => timeline-line-faded.
Changed a before action that was checking approver ACLs to also happen in proposal mode
Made a series of changes to reduce how often we were going to CMR to check approver acls
Added a badge that displays approver/user status in dMMT
Added submitter column to index pages (sorting deferred)
Added ingest error display when publishing a proposal fails
Made a series of changes to maintain output consistency (e.g. cancel, word order)
Updated variable names draft => proposal in proposal files
=> MMT-2000 Odds and ends update based on PO walkthrough

app/concerns/proposal_index.rb, app/controllers/manage_proposal_controller.rb, app/controllers/proposal/collection_draft_proposals_controller.rb, app/helpers/proposals_helper.rb, app/models/collection_draft_proposal.rb, app/views/manage_proposal/show.html.erb, app/views/proposal/collection_draft_proposals/index.html.erb, db/migrate/20200107163307_add_submitter_column.rb, db/schema.rb, spec/features/manage_proposals/approver_workflow_spec.rb, spec/features/manage_proposals/manage_proposal_publish_spec.rb, spec/features/manage_proposals/manage_proposal_view_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_create_from_collection_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_list_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_submit_spec.rb, spec/features/proposal/manage_collection_proposals/open_proposals_spec.rb, spec/support/approved_proposals_helpers.rb, spec/support/proposal_status_helper.rb
And updating sorting on the various index/manage proposal pages to enable sorting by submitter.
Migration to add the user_id of the person who created the record if there is no submitter_id.  This decision was made because it simplified the migration and did not add urs_uid's to our repo.
=> MMT-2067 Updating schema to include a column for submitter

spec/support/ajax_helpers.rb
When I looked at where this error was occurring, I noticed that it seemed to be related to provider context switching.  One of the things that happens in that context is page loading while under the loop in wait_for_jquery.  
My hypothesis is that jQuery.active was being called after a page load was triggered and before jQuery had been loaded, so it was not defined.  
If the problem rested with some greater jQuery being undefined issue, I would expect the loop in wait_for_jquery to never end.  I think that my hypothesis is supported by this change being tested in bamboo 8 times and not hanging infinitely.  If the observed rate of success before the change was roughly 1 in 3, 8 successes in a row is something like 1 in 6500.
=> MMT-2125 Mitigating jquery not defined problems in bamboo

app/controllers/proposal/collection_draft_proposals_controller.rb, app/mailers/proposal_mailer.rb, app/views/proposal_mailer/proposal_submitted_approvers_notification.html.erb, app/views/proposal_mailer/proposal_submitted_approvers_notification.text.erb, spec/features/manage_proposals/approver_workflow_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_submit_spec.rb, spec/mailers/previews/proposal_mailer_preview.rb, spec/mailers/proposal_mailer_spec.rb, spec/support/approved_proposals_helpers.rb
Updated how I was getting the approvers' URS to send the submission e-mails.  This method would tie the e-mails to whomever has the create permissions for approvers in SCIOPS.
=> MMT-1719 Approver E-mails when a Proposal is Submitted

Gemfile, Gemfile.lock, spec/features/collection_templates/template_index_spec.rb, spec/rails_helper.rb
Rails 5 added the necessary support to remove database cleaner.  Needed to lightly rewrite a pair of template tests to get them to pass due to the change.  Using database cleaner caused the ids to reset for each test (e.g. the first one always had an id of 1), but transactional fixtures still allows the record id to increment (e.g. each id is random based on the order the tests are run).  The tests were updated to be agnostic to this (like the rest of the tests of this nature in our codebase).
=> MMT-2031 Removing Database Cleaner

README.md
Note formatting on README.md is off when viewed from github.com.
replacing "urs_*_url" with "urs...url" to fix.
=> MMT-2132 Change urs_*_url to urs...url because of formatting issue when viewed from github.com

config/environments/uat.rb, spec/features/variables/create_collection_association_spec.rb, spec/features/variables/delete_collection_assocation_spec.rb, spec/features/variables/delete_variable_spec.rb, spec/features/variables/variable_permissions_spec.rb
CMR made a change such that you cannot associate two collections to one variable.  Some of our tests tested for that specifically and needed to be changed as a consequence.
=> MMT-2137 Adjusting tests for variable uniqueness changes in CMR

app/controllers/collections_controller.rb, lib/cmr/base_client.rb, lib/cmr/response.rb, spec/cmr/response_spec.rb, spec/features/users/user_login_spec.rb
Added a helper method to replace the token in an error message with "Token beginning with <first 6 characters>...".
Applied helper method whenever the errors are being checked/set.
Made sure that clean inspect checks/sets the errors before returning a string containing them
Checked where we were using inspect vs clean_inspect and changed to clean_inspect when possible
=> MMT-2126 Stop displaying/logging tokens returned by CMR in error messages

app/controllers/base_published_record_controller.rb, app/controllers/variable_drafts_controller.rb, config/locales/en.yml, lib/assets/schemas/variables/umm-var-form.json, lib/cmr/response.rb, lib/json_schema_form/umm_form.rb, spec/factories/variable_draft_factories.rb, spec/features/variable_drafts/create_variable_draft_from_variable_spec.rb
Updated the flash message when a variable fails to ingest because we submitted a record which changed the name (not allowed per CMR). 
Added comments to make finding the conversion of variable/service_drafts to published variables/services more apparent for unknowing developers.  Collection drafts publish; Variable and Service drafts create new variables/services.  I feel that these should have been implemented the same way.
Added logic when making the forms for variables/services that allows for marking some fields as readonly based on the conditions at the time of rendering the forms (previously the schema was static)
Disabled the name field when querying the CMR finds a provider+native id to match the current record.
=> MMT-2009 Disabled variable name field when provider_id + native_id is found in CMR.  Updated flash for name uniqueness

app/assets/javascripts/draft_form_selectors.coffee, app/assets/javascripts/required_fields.coffee, app/assets/javascripts/validation.coffee, app/views/collection_drafts/forms/fields/_horizontal_data_resolution_fields.html.erb, db/schema.rb, spec/factories/collection_factory_data.rb, spec/features/collection_drafts/forms/radio_button_selectors_spec.rb, spec/features/collection_drafts/forms/spatial_information_form_spec.rb, spec/features/collection_drafts/forms/validation_spec.rb, spec/features/collection_previews/spatial_information_preview_spec.rb, spec/features/collection_templates/template_creation_spec.rb
Updated JS for draft forms to clear checkboxes and to prevent checkboxes from clearing radio button values
Reverting required fields JS to check the top required data level (seems to be important to variable/service draft required fields)
Adding schema path to a variety of errors so that they can be properly processed (threw errors without it)
Updating tests/field names to help get tests to pass
=> MMT-1726 fixing broken tests in UMM-Cv1.15 update by updating validation, form clearing, and required icons

Gemfile, Gemfile.lock
Adding ref to cmr_preview_gem containing the fix for related_urls that don't show up in the preview.
=> Changed ref to point to latest cmr_preview_gem.

app/assets/stylesheets/components/_metadata-preview.scss, app/assets/stylesheets/overrides/_eui.scss, app/concerns/cmr_subscriptions.rb, app/controllers/subscriptions_controller.rb, app/views/subscriptions/edit.html.erb, app/views/subscriptions/index.html.erb, app/views/subscriptions/show.html.erb, lib/cmr/cmr_client.rb, spec/features/manage_cmr/subscriptions/create_subscriptions_spec.rb, spec/features/manage_cmr/subscriptions/delete_subscriptions_spec.rb, spec/features/manage_cmr/subscriptions/edit_subscriptions_spec.rb, spec/features/manage_cmr/subscriptions/index_subscriptions_spec.rb, spec/features/manage_cmr/subscriptions/show_subscription_spec.rb, spec/support/subscriptions_helpers.rb
Updated Index controller and view actions to read from CMR
Updated Show/Edit/Update/Destroy to only require a (concept_)id to be passed
Created a before action for Show/Edit/Update/Destroy to find the rest of the information they need from CMR
Updated Edit/Delete buttons where necessary
Updated get_subscriptions
Updated tests - note: the after block deletes could be removed if we could correctly use reset_provider, but it does not work correctly because there is a bug in CMR (ticket written).
=> MMT-2198 Reading Subscriptions from CMR

Gemfile, Gemfile.lock, app/assets/javascripts/draft_form_selectors.coffee, app/views/collection_drafts/forms/fields/_horizontal_data_resolution_fields.html.erb, app/views/collection_drafts/forms/fields/_spatial_extent_fields.html.erb, spec/features/collection_drafts/forms/spatial_information_form_spec.rb
Updated views such that when the page loads, they display if either the spatial_coverage_type dictates they should or if there is already data in the fields.
Updated JS to not clear fieldsets if the displayed fields are a subset of the new spatial_coverage_type
=> MMT-2186 Displaying spatial extents if they are present

app/controllers/collection_drafts_controller.rb, app/controllers/proposal/collection_draft_proposals_controller.rb, spec/features/collection_drafts/publish_collection_draft_spec.rb, spec/features/manage_cmr/subscriptions/subscription_form_validation_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_submit_spec.rb
Renamed show_view_setup to collection_validation_setup because it needs to be run in all of the places we run validate_metadata.
Added verify_valid_metadata as a before action for publish action to repeat the validation that was run when the show page was loaded.
Added before actions for the submit action (proposals) to load the schema, run collection_validation_setup, and run the validation
=> MMT-2195 Perform validation before publish and submit

Gemfile, Gemfile.lock
Relates to additional attributes changes in preview gem display. They should now display without needing an ancillary keyword or isotopic category and should display their table only when applicable.
=> MMT-2045 updating preview gem commit ref

app/concerns/cmr_collections_helper.rb, app/controllers/manage_metadata_controller.rb, spec/features/collections/revision_list_spec.rb, spec/features/services/revision_list_spec.rb, spec/features/tools/revision_list_spec.rb
CMR does not sort by revision date first by default.  In order to ensure the behavior we expect, we need to tell it to sort by revision date.
=> Hotfix/MMT-2231-1 Updating revisions helpers to sort by revision date

app/views/base_published_record/_delete_link.html.erb, app/views/base_published_record/_delete_modal.html.erb, app/views/services/show.html.erb, app/views/tools/show.html.erb, app/views/variables/show.html.erb, spec/features/provider_context/provider_context_spec.rb
Having the modal in the same partial as the link causes a line break.  Separated them so that the display remains the same as before.
=> Hotfix/MMT-2301-1 Moving delete modal to separate partial

Gemfile, Gemfile.lock, app/helpers/collections_helper.rb, app/views/collections/show.html.erb
- added an `edsc_url` method to read the current MMT environment (sit,prod,uat,etc) and return the proper edsc url for passage to the preview gem
=> MMT-1876: Link SKW, Data Centers, instruments, and platforms in a collection's preview to Earthdata Search collections with the same keywords

db/migrate/20200903193441_umm_v_1_7_data_migration.rb, spec/migrations/umm_v_1_7_spec.rb
Data migration failed because there were existing drafts which had a string for characteristics and strings do not respond to dig.
=> MMT-2325 updating data migration to account for improperly formatted existing variables

app/assets/javascripts/change_current_provider.coffee, app/assets/javascripts/collections.coffee, app/controllers/application_controller.rb, app/controllers/collections_controller.rb, app/helpers/collections_helper.rb, app/helpers/modals_helper.rb, app/views/collections/show.html.erb, app/views/shared/_not_current_provider_modal.html.erb, spec/features/collections/delete_collection_spec.rb, spec/support/vcr.rb
* add getting variable count on collections show page
* modify modal to display proper messages for granules and/or variables
* ensure workflows for deleting collection with granules or variables all work
* update tests for deleting collection
* add helper methods for modal close links and use on collections show page
* some whitespace changes in application controller to appease rubocop
* add try/catch for echo provider token in development
=> MMT-2331: notify user of associated variable when deleting collection

app/controllers/base_published_record_controller.rb, app/controllers/cmr_search_controller.rb, app/controllers/collection_associations_controller.rb, app/controllers/manage_metadata_controller.rb, app/controllers/variable_drafts_collection_searches_controller.rb, app/controllers/variable_drafts_controller.rb, app/helpers/manage_metadata_helper.rb, app/views/cmr_search/shared/_search_results.html.erb, app/views/collection_associations/edit.html.erb, app/views/collection_associations/index.html.erb, app/views/drafts/shared/_collection_association_progress_panel.html.erb, app/views/variable_drafts_collection_searches/new.html.erb, config/locales/en.yml, config/routes.rb, spec/features/collections/downloading_xml_spec.rb, spec/features/proposal/search/collection_search_spec.rb, spec/features/services/download_json_spec.rb, spec/features/tools/download_json_spec.rb, spec/features/variable_drafts/create_variable_draft_from_variable_spec.rb, spec/features/variables/download_json_spec.rb, spec/features/variables/manage_collection_association_spec.rb, spec/features/variables/reverting_variable_spec.rb, spec/features/variables/variable_with_draft_spec.rb
Allowed user to update collection association from published variable's 'manage collection association' page.
Allowed user to update collection association for drafts which have published counterparts.
Updated logic for reverting a variable to always use the association of the last non-deleted revision.
Updated wait time on download json tests
=> MMT-2367 Update Variable Collection Association

spec/features/proposal/deleting_old_proposals_spec.rb
`<App>::Application.load_tasks` causes rake to define tasks.  If tasks have already been defined this causes them to be added together. This was causing duplication of the reset_provider function which was ultimately causing CMR to run out of memory.  
This branch + it-2 have run 10 times with these changes and passed 9 of them.  The failure case was for a different intermittent issue, so I think this change resolves the main thrust of this ticket.
=> MMT-2384 Preventing test from redefining rake tasks

Gemfile, Gemfile.lock, lib/json_schema_form/umm_preview_elements/umm_preview_link.rb, spec/features/service_drafts/preview/valid/service_information_preview_spec.rb
Updating preview gem commit to take care of rendering URLs that turn into routes in rails.
Updating same problem in MMT json schema previews.
=> MMT-2386 updating preview gem and removing same error from json schema previews in MMT

app/assets/stylesheets/components/_preview-gem-cards.scss
=> MMT-2386 removing text-decoration underline as previously intended

app/assets/javascripts/change_current_provider.coffee, app/controllers/base_drafts_controller.rb, app/controllers/variable_drafts_controller.rb, app/views/collection_drafts/forms/_archive_and_distribution_information.html.erb, app/views/collections/show.html.erb, app/views/drafts/new.html.erb, app/views/manage_variables/show.html.erb, app/views/shared/_not_current_provider_modal.html.erb, config/routes.rb, spec/features/variable_drafts/create_variable_draft_with_associated_collection_spec.rb
- Added text field on manage variables page for user to supply concept-id of collection they want to associate the variable with
- Added link on collection show page that allows a user to create an associated variable draft
- added functionality to the _not_current_provider_modal and change_current_provider.coffee files so that the not-current-provider-modal is displayed when a user clicks on the 'Create Associated Variable' link 
- added a child `new` method to the variable_drafts_controller
=> MMT-2355: Create a variable draft with the associated collection filled out

db/migrate/20201013182007_umm_s_1_3_4_data_migration.rb, db/schema.rb, spec/factories/data_migration_factories/umm_s_1_3_4_factory.rb, spec/migrations/umm_s_1_3_4_spec.rb
I took the logic from CMR's data migration and implemented it on our drafts.  The logic wrt to the new Subset fields was tailored to the existing data in CMR prod.
After my last migration ran into bad data, I tried to make this one a little more robust about what happens when it encounters bad data.  My approach was to delete malformed data in the draft and abort the current operation. This may preserve bad drafts, but it also allows for partial success in this migration.  
Closed and reopened because I pushed another ticket's work onto this branch.
=> MMT-2389 data migration for UMM-S v 1.3.4

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_metadata-preview.scss, app/concerns/cmr_collections_helper.rb, app/controllers/collection_drafts_controller.rb, app/controllers/collections_controller.rb, app/views/collection_drafts/show.html.erb, app/views/collections/show.html.erb, app/views/manage_tools/show.html.erb, app/views/proposal/collection_draft_proposals/show.html.erb, app/views/proposal/collections/show.html.erb, lib/tasks/testing.rake, spec/features/collection_drafts/create_collection_draft_from_collection_spec.rb, spec/features/collection_previews/service_and_tool_tab_spec.rb, spec/features/proposal/collection_draft_proposals/collection_draft_proposal_create_from_collection_spec.rb, spec/tasks/ingesting_cmr_data_spec.rb
Updated css so services and tools match.
Updated get_associated_services to get_associated_concepts and it gets both services and tools.
Uncommented text on Manage Tools page
Added a helper rake task that ingests and associated specified numbers of tools and services to save time manual testing
Added tests for service and tool tab metadata and javascript, also for helper task.
=> MMT-2366 Adding tools tab

app/controllers/manage_cmr/service_option_assignments_controller.rb, spec/controllers/service_option_assignments_controller_spec.rb
- Checked controller actions to verify which parameters we were explicitly using. Documented above permitted params method
- Updated destroy action so that it uses permitted params method
- Added test to verify the expected keys.
=> MMT-2422 Adjusting permitted parameters so that we aren't blocking the service option assignment workflow

app/assets/javascripts/required_fields.coffee, app/assets/javascripts/umm_forms.coffee, app/views/collection_drafts/forms/fields/_geometry_fields.html.erb, app/views/collection_drafts/forms/fields/_horizontal_data_resolution_fields.html.erb, lib/json_schema_form/umm_form_elements/umm_checkbox_dependent_fields.rb, spec/features/collection_drafts/forms/spatial_information_form_spec.rb, spec/features/collection_drafts/forms/unselect_radio_buttons_spec.rb
- Added extra listener for `show-hide-checkboxes` 
- Added data field for `show-hide-checkboxes` so functionality can be shared between `dependent-fields-checkboxes`
- wrote tests that mimic the error recreation on the ticket
=> MMT-2452: Draft Forms add too many required icons (radio buttons with 'clear' link)

app/assets/javascripts/accordion.coffee, spec/features/collection_drafts/form_accordions_spec.rb, vendor/assets/javascripts/eui-1.0.0/eui.js
- Adjusted eui.js handler
- uncommented spec
=> MMT-951: On Metadata Draft Forms, clicking on the info button on a subform will open/close the accordion as well as showing the help modal.

app/assets/javascripts/validation.coffee, spec/features/collection_drafts/forms/data_identification_form_spec.rb, spec/features/collection_previews/data_identification_preview_spec.rb, spec/features/manage_cmr/subscriptions/create_subscriptions_spec.rb, spec/support/draft_helpers.rb
* don't show validation error for License Text (shows up when License URL is chosen)
* modify data identification tests to prevent cascading errors
=> MMT-2541: hotfix

app/controllers/manage_cmr_controller.rb
- the merge of MMT-2591 caused a bug - specifically `TypeError (no implicit conversion of String into Integer)` for the EDF_DEV07 provider
- this was investigated (splunk logs revealed the error message). The error was caused by a simple bug in the code where a `.map` method was called on an object that was expected to be an `Array` but was a `Hash`.
- the appropriate changes were made - just had to move a parenthesis.
=> hotfix/MMT-2591-1: Fix SIT-test error that was occurring for provider EDF_DEV07

app/controllers/collection_drafts_controller.rb, app/helpers/form_helper.rb, app/helpers/preview_circles_helper.rb, app/views/collection_drafts/forms/_collection_information.html.erb, app/views/collection_drafts/forms/_data_centers.html.erb, app/views/collection_drafts/forms/_data_contacts.html.erb, app/views/collection_drafts/forms/fields/_tiling_identification_system_fields.html.erb, spec/features/collection_drafts/forms/country_selection_spec.rb, spec/features/collection_drafts/forms/required_fields_spec.rb
- added `label_id`'s to the appropriate labels, and adjusted the `for` attribute logic in `mmt_label` so that the `for` attribute is added regardless of the presence of the label's id. This is permissible now because the `label_id` no longer equals the input field's id because of the appended `_label` text to the `label_id` 
- For peace of mind I checked everywhere the `set_id` (now called `label_id`) parameter was being used and found that the only place it was being used, it was not needed - in fact, it was causing a bug
- fixed a preexisting bug where Tiling Identification System > Coordinates 1&2 were not getting required icons when they should have been (by removing the `set_id` parameter)
- adjusted the anchors of all appropriate progress circles
- I did not feel the need to write …
=> MMT-2486: UMM-C draft progress circle links do not take users to appropriate field

config/environments/uat.rb
In the previous hotfix, csp logs were turned off during the development process and never turned back on.
=> hotfix/MMT-2534: turn csp logs back on

app/assets/javascripts/validation.coffee, app/controllers/collection_drafts_controller.rb, spec/features/collection_drafts/forms/validation_spec.rb
- since I reversed the logic of the switch statements a few commits back, the -String data types were being validated incorrectly because there were no switch statements to handle the string values. The `errorNotPresent` and `error_not_present` variables were remaining `null` and `nil` respectively and thus triggering validation failure. 
- I added the fix and some tests to ensure this is caught in the future. Admittedly, the tests should have been there in the first PR
=> hotfix/MMT-2543: added tests; fixed bug

app/assets/javascripts/data_management.coffee, app/assets/javascripts/order_option_assignments.coffee, app/assets/javascripts/order_policies.coffee, app/assets/javascripts/permissions.coffee, app/assets/javascripts/service_management.coffee, app/assets/javascripts/widgets/Chooser/Chooser.coffee, app/assets/stylesheets/components/_icons.scss, app/concerns/chooser_endpoints.rb, config/environments/development.rb, spec/features/chooser/chooser_disable_selected_options.rb, spec/features/chooser/chooser_to_filter_spec.rb, spec/fixtures/cmr_search.json
- Adjusted method to add `s3-links` for Chooser widget consumption
- Adjusted Chooser widget to show s3 icon and buckets if s3 links are available
- wrote tests
=> MMT-2655: Update the chooser-widget to visually show which collections have s3 access

app/controllers/manage_proposal_controller.rb, lib/cmr/cmr_client.rb, spec/features/manage_cmr/subscriptions/index_subscriptions_spec.rb, spec/features/manage_cmr/subscriptions/show_subscription_spec.rb
Adds test user to local URS/EDL before creating subscription as CMR wiill check to ensure user exists in EDL. Added include_granule_counts to CMR collection query, as deleting a collection requires a check to ensure there are no granules and this info was missing.
=> Mmt 2814 - Fixed build failures from latest changes to CMR.

app/assets/javascripts/drafts.coffee, app/controllers/collection_drafts_controller.rb, app/controllers/collections_controller.rb, app/controllers/manage_metadata_controller.rb, app/views/collections/revisions.html.erb, spec/features/collection_drafts/progressive_update_collection_spec.rb, spec/features/collection_drafts/publish_collection_draft_spec.rb, spec/support/ingest_helpers.rb
* handle both error formats - array of messages, or hash with path and error attributes
* update to use generate ingest errors
* update flash messages
* update modal messages
* update tests
=> MMT-2707: handle both ingest error formats from CMR 

app/concerns/controlled_keywords.rb
Fixed a bug that Francell found during testing where in Tool Contact when a user tries to select 'Country', the option for United States was not at the top.
=> MMT-3159: Upgrade rails to 6.0

app/controllers/manage_cmr/permissions_controller.rb, spec/features/collection_drafts/publish_collection_draft_spec.rb
Ensures that the ACL groups presented are distinct, looks like some data got corrupted and ACL groups where duplicated.
=> MMT-3155: Ensures that the ACL groups presented are distinct

package.json, yarn.lock
I was able to fix one high, and 81 moderates total, and now only 5 moderates remaining.  These 5 moderates regarding to word-wrap package and all current versions have moderate vulnerability.  Currently there is no fix for it yet
https://snyk.io/advisor/npm-package/word-wrap
=> MMT-3324: June 2023 MMT GitHub Vulnerability

config/environments/development.rb, config/environments/production.rb, config/environments/sit.rb, config/environments/test.rb, config/environments/uat.rb, lib/cmr/cmr_client.rb
Currently users are experience really slow load times in MMT.   Rosy and I did some analysis of the logs and it is showing retrievals of keywords from CMR in minutes.
This a hot fix branch that is based on what is currently in UAT.   The purpose of this code is to make the keyword cache held by MMT configurable.   With this change, you can set a bamboo variable `cmr_keyword_cache_expires_in`, currently the default is 14400 seconds (4 hours).   The plan is to test and move this through the env's quickly tomorrow, than rollback the existing env.
=> MMT-3466: Increase keyword cache to 4 hours

app/middleware/middleware_healthcheck.rb
Update the MMT status page to only check the status of MMT database.
https://mmt.earthdata.nasa.gov/status
{"database": true}
=> MMT-3080: Update MMT Status page to only check status of MMT database

index.html, static/src/css/initial/index.scss, static/src/css/vendor/bootstrap/_variables.scss, static/src/css/vendor/bootstrap/overrides/_navbar.scss, static/src/js/App.jsx, static/src/js/components/Button/Button.jsx, static/src/js/components/Header/Header.jsx, static/src/js/components/Header/Header.scss, static/src/js/components/Header/__tests__/Header.test.js, static/src/js/components/ManageSection/ManageSection.jsx, static/src/js/components/ManageSection/ManageSection.scss, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.js, static/src/js/components/Page/Page.jsx, static/src/js/components/Page/Page.scss, static/src/js/components/Panel/Panel.jsx, static/src/js/components/Panel/Panel.scss, static/src/js/components/Panel/__tests__/Panel.test.js, static/src/js/pages/HomePage/HomePage.jsx, static/src/js/pages/HomePage/HomePage.scss, static/src/js/pages/HomePage/__tests__/HomePage.test.js, static/src/js/pages/ManagePage/ManagePage.jsx, static/src/js/providers/AppContextProvider/AppContextProvider.jsx, static/src/js/providers/AppContextProvider/__tests__/AppContextProvider.test.js
Adds the homepage to the application and adjusts some styling in the wrapper and header
=> MMT-3490: Adding homepage

static/src/js/App.jsx, static/src/js/__tests__/App.test.js, static/src/js/components/CollectionAssociation/__tests__/CollectionAssociation.test.js, static/src/js/components/DraftPreview/__tests__/DraftPreview.test.js, static/src/js/components/MetadataForm/MetadataForm.jsx, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.js, static/src/js/components/Notifications/__tests__/Notifications.test.js, static/src/js/components/PublishPreview/__tests__/PublishPreview.test.js, static/src/js/context/AuthContext.js, static/src/js/hooks/__tests__/useControlledKeywords.test.js, static/src/js/hooks/useAuthContext.js, static/src/js/providers/AppContextProvider/AppContextProvider.jsx, static/src/js/providers/AppContextProvider/__tests__/AppContextProvider.test.js, static/src/js/providers/AuthContextProvider/AuthContextProvider.jsx, static/src/js/providers/AuthContextProvider/__tests__/AuthContextProvider.test.js, static/src/js/providers/GraphQLProvider/GraphQLProvider.jsx, static/src/js/providers/GraphQLProvider/__tests__/GraphQLProvider.test.js, static/src/js/providers/Providers/Providers.jsx, static/src/js/providers/Providers/__tests__/Providers.test.js, static/src/js/utils/__tests__/checkAndRefreshToken.test.js, static/src/js/utils/checkAndRefreshToken.js
This PR reorganizes the creates a new provider for authorization `AuthContextProvider`, separate from the app context,  and a new `GraphQLProvider` component that instantiates the Apollo provider, and moves them both into the Providers component. The `AppContext` now uses the AuthContext to grab the user authentication information and store it for global use.
This creates the following structure
```jsx
<AuthProvider> // Deals with authentication
<AppContextProvider> // Stores app wide state
<GraphQLProvider> // initializes Apollo
<NotificationsProvider> // Notifications
<App/>
</NotificationsProvider>
</GraphQLProvider>
</AppContextProvider>
</AuthProvider>
```
These changes to the `Providers` component will prevent us from being limited when trying to use any of the Providers within …
=> MMT-3595: Reorganizing context and providers

serverless/src/samlCallback/handler.js, static/src/js/components/AuthCallbackContainer/AuthCallbackContainer.jsx, static/src/js/components/AuthCallbackContainer/__tests__/AuthCallbackContainer.test.js, static/src/js/providers/AuthContextProvider/AuthContextProvider.jsx
This PR removes the max-age on the launchpad token, so it will clear on browser close.  It also really isn't needed once the loginInfo cookie is set, as the launchpad token gets assigned into that object with an expiration, so I'm now removing the launchpadToken cookie altogether once loginInfo cookie is set.  Earlier versions of the code also had a 'data' cookie, this caused issues with header length size because it was so large, so I'm also removing that cookie if it exists.
=> MMT-3604: Clean up cookies

static/src/js/components/PublishPreview/PublishPreview.jsx, static/src/js/components/PublishPreview/__tests__/PublishPreview.test.js, static/src/js/components/PublishPreview/__tests__/__mocks__/publishPreview.js, static/src/js/operations/queries/getCollection.js
Added granule count for a given collection on Preview Preview page.
=> MMT-3558: As a user, I can see how many granules are associated with my collection

static/src/css/vendor/bootstrap/_variables.scss, static/src/css/vendor/bootstrap/overrides/_table.scss, static/src/js/components/Button/Button.jsx, static/src/js/components/ControlledPaginatedContent/ControlledPaginatedContent.jsx, static/src/js/components/ControlledPaginatedContent/__tests__/ControlledPaginatedContent.test.js, static/src/js/components/DraftList/DraftList.jsx, static/src/js/components/EllipsisLink/EllipsisLink.jsx, static/src/js/components/Header/Header.jsx, static/src/js/components/Header/__tests__/Header.test.js, static/src/js/components/Header/__tests__/__mocks__/providerResults.js, static/src/js/components/Page/Page.jsx, static/src/js/components/Table/Table.jsx, static/src/js/components/Table/Table.scss, static/src/js/hooks/__tests__/useSearchQuery.test.js, static/src/js/hooks/useSearchQuery.js, static/src/js/operations/queries/getProviders.js, static/src/js/pages/SearchPage/SearchPage.jsx, static/src/js/pages/SearchPage/__tests__/SearchPage.test.js, static/src/js/pages/SearchPage/__tests__/__mocks__/searchResults.js
This PR adds the ability to search across additional types and providers from within the search dropdown in the header. When the user performs a search, they are navigated to the search results page with the selected parameters in the URL. This PR also tweaks some styling on the search page.
=> MMT-3493: Search filter dropdown

static/src/js/providers/AppContextProvider/AppContextProvider.jsx, static/src/js/providers/GraphQLProvider/GraphQLProvider.jsx, static/src/js/providers/GraphQLProvider/__tests__/GraphQLProvider.test.js
The request loop can be avoided by memoizing the creation of the ApolloClient, so that it is only initialized if the tokenValue changes. This prevents a new client from being created whenever the AppContext is changed.
When viewing the network tab, a request loop no longer occurs when loading drafts, searching for drafts, or when typing into the inputs on a form.
We might need to make improvements to the Contexts down the line but this should get us past the current issue and allow us some time to sort out how we would like to handle that.
=> MMT-3609: Fixes issue with looping Apollo requests

bin/deploy-bamboo.sh
Configuration used for launchpad host names are different for sandbox vs. production.   These changes allow these to be updated using bamboo variables.
The host names were set in `static.config.json` to `auth.launchpad-sbx.nasa.gov` and for production these need to be `auth.launchpad.nasa.gov`.  This change allows these host names to be updated in bamboo.
Updated `deploy_bamboo.sh` to configure `static.config.json` with the proper launchpad host names.
This impacts deployments, particuarly being able to deploy to UAT and eventually OPS.
Currently, if you click Login with Launchpad button on https://mmt.uat.earthdatacloud.nasa.gov it will redirect to `auth.launchpad-sbx.nasa.gov`.  It should redirect to `auth.launchpad.nasa.gov`
Please include relevant screenshots or files that would be …
=> MMT-3680: Updated deploy_bamboo.sh to update launchpad host names.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
This should be how PRs for this repository look from now on. These files exist in MMT-3390 so we are just moving them to the master branch in the hopes this template will start to show up. 
Added .github file from MMT-3390 to master branch. 
All future PRs
Not sure how to test this without merging it first. Open to suggestions!
N/A
=> MMT-3696: Add pull request template to MMT repository

static/src/js/components/OrderOption/OrderOption.jsx, static/src/js/components/OrderOptionForm/OrderOptionForm.jsx, static/src/js/components/OrderOptionForm/__tests__/OrderOptionForm.test.jsx, static/src/js/components/OrderOptionList/OrderOptionList.jsx, static/src/js/components/OrderOptionList/__tests__/OrderOptionList.test.jsx, static/src/js/operations/mutations/deleteOrderOption.js, static/src/js/operations/queries/getOrderOptions.js, static/src/js/pages/OrderOptionPage/OrderOptionPage.jsx, static/src/js/pages/OrderOptionPage/__tests__/OrderOptionPage.test.jsx, static/src/js/schemas/orderOption.js, static/src/js/schemas/uiSchemas/OrderOption.js
Adding the ability to delete and deprecate an order option
=> MMT-3515: As a user, I can delete Order Option

static/src/js/App.jsx, static/src/js/__tests__/App.test.jsx, static/src/js/components/Group/Group.jsx, static/src/js/components/ProviderPermissions/ProviderPermissions.jsx, static/src/js/components/ProviderPermissions/__tests__/ProviderPermissions.test.jsx, static/src/js/constants/providerIdentityPermissions.js, static/src/js/constants/systemIdentityPermissions.js, static/src/js/operations/queries/getAcls.js, static/src/js/operations/queries/getProviderIdentityPermissions.js, static/src/js/pages/GroupPage/GroupPage.jsx, static/src/js/pages/ProviderPermissionsPage/ProviderPermissionsPage.jsx, static/src/js/pages/ProviderPermissionsPage/__tests__/ProviderPermissionPage.test.jsx
Adds the permissions form for Provider lever permissions that apply to a group.
Added the checkbox table / form that _shows_ the permissions and which permissions are selected for a given group.
Group Provider level permissions.
=> MMT-3526: Implements the Provider Permissions form for groups.

static/src/js/components/PermissionList/PermissionList.jsx
When testing collection permission in SIT, noticed that clicking on a permission was navigating /undefined
=> MMT-3529: As a user, I can view all collection permissions

Gemfile, Gemfile.lock, package.json
Update package.json and Gemfile to fix vulnerabilities.
Rails side:
Updated to the latest 6.1 minor version of rails (6.1.7.7)
Did not update "rack", upgrade path is beta, so since medium vulnerability, will wait on this one.
Updated rexml gem to the latest version.
actionable means going to rails 7, also medium vulnerability so not updating.
React side:
Upgraded braces and micro match to their respective patch versions.
Rails MMT
yarn audit should be clean
bundle-audit check --update should be clean
=> MMT-3741: Updates to gems and node modules.

static/src/js/components/AuthRequiredLayout/AuthRequiredLayout.jsx, static/src/js/operations/queries/getAvailableProviders.js
Fixes the GraphQLProvider cache keys for the getAvailableProviders query, by requesting the conceptId of the acl to be returned
/providers page, ChooseProviderModal
Navigate to /providers, ensure that the same provider isn't listed for every list item
=> MMT-3631: Fixes cache of available providers

static/src/js/components/ProviderPermissions/ProviderPermissions.jsx, static/src/js/components/ProviderPermissions/__tests__/ProviderPermissions.test.jsx, static/src/js/components/SystemPermissions/SystemPermissions.jsx, static/src/js/components/SystemPermissions/__tests__/SystemPermissions.test.jsx
There was a default causing incorrect messaging to appear on successful saves on permission forms.
Removed the default, it wasn't necessary and was causing issues.
=> MMT-3682: Corrects checks related to messaging in permissions forms

static/src/js/components/FormNavigation/FormNavigation.jsx, static/src/js/components/FormNavigation/__tests__/FormNavigation.test.jsx, static/src/js/components/MetadataForm/MetadataForm.jsx, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.jsx, static/src/js/components/TemplateForm/TemplateForm.jsx, static/src/js/components/TemplateForm/__tests__/TemplateForm.test.jsx, static/src/js/schemas/uiSchemas/collections/dataIdentification.js
The useConstraints field can be difficult to understand, as it selecting a type moves fields around.
This PR moves the required fields to the top of the useConstraints section, so no matter which type option you select, the fields you are required to complete are the first fields you see.
Collection form, Data Identification, useConstraints
Create a new collection draft and navigate to the Data Identification form. Under Use Constraints select each of the options
* "Description without License URL or Text." will show the Description field as required directly under the select field.
* "License URL" will show the License URL field as required directly under the select field.
* "License Text" will show the License Text field as required directly under the select field.
=> MMT-3639: Rearrange useConstraints fields to be easier to use

static/src/js/components/FormNavigation/FormNavigation.jsx, static/src/js/components/FormNavigation/__tests__/FormNavigation.test.jsx, static/src/js/components/TemplateForm/TemplateForm.jsx, static/src/js/components/TemplateForm/__tests__/TemplateForm.test.jsx, static/src/js/pages/MetadataFormPage/MetadataFormPage.jsx, static/src/js/utils/__tests__/updateTemplate.test.js, static/src/js/utils/getTemplate.js, static/src/js/utils/updateTemplate.js
Fixes a bug where the provider selection modal would not appear when saving a new draft or template on nested form pages.
Added a check for the conceptId of "new" on `if` statement wrapped around function that triggers the modal.
New drafts/templates forms
- **Environment for testing:** N/A
- **Collection to test with:** N/A
1. Create a new draft
2. Click on a different form section
3. Confirm the modal appears
4. Save the draft
5. Confirm the provider selection modal applies the correct provider
=> MMT-3738: Fix provider selection bug

bin/deploy-bamboo.sh, serverless-configs/aws-cors-configuration.yml, serverless/src/samlRefreshToken/handler.js, static/src/js/providers/GraphQLProvider/GraphQLProvider.jsx, static/src/js/providers/GraphQLProvider/__tests__/GraphQLProvider.test.jsx
If the user has been active during the lifespan of their token, we want to auto-refresh the token for them so they don't have to be redirected. If they have been idle throughout their token, they will still be redirected to login again.
Refreshing tokens
Login, wait for 14 minutes and you will see a call to `saml-refresh-token` in dev tools. If you wait another 14 minutes you will see a console log of "LOG OUT WARNING", which means your token will expire in 60 seconds. 
Any interaction with the website will reset your 'idle' state (mouse moves, keystrokes, etc.) and keep you logged in
=> MMT-3749: Updates CORS settings for token refreshing

package-lock.json, package.json, static/src/js/components/MetadataForm/MetadataForm.jsx, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.jsx, static/src/js/components/MetadataPreview/MetadataPreview.jsx, static/src/js/components/MetadataPreview/__tests__/MetadataPreivew.test.jsx, static/src/js/components/TemplatePreview/TemplatePreview.jsx
* Fixes metadata download links (point to correct CMR, and hide links for drafts)
* Use the existing draft provider when saving the draft
* Updates metadata-preview library
* Metadata Preview, viewing published concepts and drafts
* Saving drafts
* Fixes metadata download links (point to correct CMR, and hide links for drafts)
* View a published concept, the Metadata Download buttons should point to the correct CMR env
* View a draft, no Metadata Download buttons will be present
* Use the existing draft provider when saving the draft
* With multiple providers available to you, create a new draft, with any provider except the first in the modal dropdown
* Make a change to the metadata and save again
* Ensure in the URL that the concept ID remains on the original provider you selected
* …
=> MMT-3769: Fixes metadata download links, MMT-3768: Use draft's provider when saving draft

static/src/js/schemas/uiSchemas/collections/dataContacts.js
Two of our enum fields were requesting controlled keywords from CMR instead of using the schema enum values. We have to use the schema enum fields in order for validation to succeed
Collection Form
Open a new draft, navigate to the Data Contacts form
Data Contacts -> Contacts Groups -> Contact Information -> Related URLs
* URL Content Type = “DistributionURL”
* Type = Use Service API
* Subtype = Opendap Data, 
* In the Get Service section, selecting any entry from the ‘Mime Type’ drop down list should not produce a validation error
=> MMT-3623: Fixes enum fields in Related URLs

bin/deploy-bamboo.sh
When deploying MMT to production, there were a few characters in the string that were being interpolated when writing EDL_PASSWORD to the .env file, as a result, it would base64 encode the wrong password used for EDL queries.
The EDL_PASSWORD should not be written to a .env file, but rather includes as a env parameters to docker.
Deployments
In prod, you should now be able to login.
=> MMT-3726: Removed code that writes to .env as not needed and causing issues with writing password with special characters in it.

bin/deploy-bamboo.sh
The link for 'Preview on Map' was using the CMR_HOST in the deployment script. I added the correct values to the deployment system and updated the script to use the new value.
=> MMT-3673: Fixes 'Preview on Map' link

static/src/js/components/PermissionList/PermissionList.jsx, static/src/js/components/PermissionList/__tests__/PermissionList.test.jsx, static/src/js/pages/PermissionPage/PermissionPage.jsx, static/src/js/pages/PermissionPage/__tests__/PermissionPage.test.jsx
Adding support for deleting a collection permission
=> MMT-3536: As a user, I can delete a collection permission

bin/deploy-bamboo.sh, static.config.json, static/src/js/components/PreviewMapTemplate/PreviewMapTemplate.jsx, static/src/js/components/PreviewMapTemplate/__tests__/PreviewMapTemplate.test.jsx
The code expected the environment variable to include the correct path in EDSC to display the spatial area on the map, but all the other 'host' parameters we use are just the host. This PR adjusts that logic to only pull the `edscHost` from configs, and moves the path to where it is used.
=> MMT-3673: Moves the search path out of the host parameter for Preview on Map logic

bin/deploy-bamboo.sh, index.html, static.config.json, static/src/js/components/Layout/Layout.jsx, static/src/js/components/Layout/Layout.scss, static/src/js/components/Layout/__tests__/Layout.test.jsx, static/src/js/components/PageHeader/PageHeader.jsx
- Inform the user of their current environment
- Show a warning banner in the production environment
- Added a banner at the top of the page when in production (based on a bamboo flag)
- Added a badge to the sidebar with the current environment for all envs except production
- Minor css changes
- Layout.jsx
- **Environment for testing:** N/A
- **Collection to test with:** N/A
1. Verify the banner exists when in the production environment
2. Verify the badge exists when in dev, sit, and uat environments
=> MMT-3787: Adding production warning and environment badges

static/src/js/components/CollectionSelector/CollectionSelector.jsx, static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx
During SIT testing, Francell found that pressing enter for the Collection Selector search was submitting the form.
For the search I have disabled the Enter keyDown by using `event.preventDefault()`
=> MMT-3776: Issues found testing collection permissions

static/src/js/components/PublishPreview/PublishPreview.jsx, static/src/js/components/PublishPreview/__tests__/PublishPreview.test.jsx, static/src/js/utils/removeMetadataKeys.js
A user testing in UAT reported that they were unable to clone a Collection record. They were getting an error 
`Uncaught TypeError: property "ShortName" is non-configurable and can't be deleted`
The ummMetadata object that coming from graphql response is `non-configurable` because of this we cannot perform any modification on that object
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_delete
The solution for this issue is to create a clone of the object which will allow us to modify the object and return the new object.
=> MMT-3804: User cannot clone a collection record

static/src/js/components/OneOfField/OneOfField.jsx
User reported that DOI field was not being auto selected on the first render when field was filled out. 
After further investigation, all of the oneOf field were having the same issue where if an option is selected for the oneOf field, the selected option was not being auto populated when the form rended. 
The fix for this was to add the logic that will update the state from rjsf repo. https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/fields/MultiSchemaField.tsx
```
if (newState !== this.state) {
this.setState(newState)
}
```
=> MMT-3806: Populate DOI & DOI Authority in edit mode for new MMT-UAT

static/src/js/components/FormNavigation/FormNavigation.jsx, static/src/js/components/FormNavigation/__tests__/FormNavigation.test.jsx, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.jsx, static/src/js/pages/DraftPage/DraftPage.jsx, static/src/js/pages/DraftPage/__tests__/DraftPage.test.jsx
As an MMT operator, don't allow me to attempt to publish a draft until the metadata will pass ingest without errors
Disables the "Publish" button on the preview page when the metadata record has errors.
Disables the "Save and Publish" button in the navigation menu when the metadata record has errors.
This also has another use case when the form shows no errors, yet since the user hasn't saved the record yet, the the validator is still giving back errors because the metadata specification hasn't been populated yet (this happens on the first save).   So if this is the case, I'm providing a tooltip over the disabled button stating the user must save the record in order to publish.
Navigation menu
Preview Page
Try creating a metadata record that has errors.   You should not be able to publish …
=> MMT-3784: Added support to disable publish button if any errors are found.

static/src/js/components/CustomTextWidget/CustomTextWidget.jsx, static/src/js/components/CustomTextWidget/__tests__/CustomTextWidget.test.jsx, static/src/js/components/PermissionForm/__tests__/PermissionForm.test.jsx
Fixed issue: Firefox and Safari do not prevent input of non numeric characters in number input fields.
Filter out non numeric characters in onChange method
Number input fields, for example Size in RelatedURL
Using Firefox (Safari)
- Go to https://mmt.sit.earthdatacloud.nasa.gov/
- Edit a Draft
- In RelatedURL, choose 'DistributionURL' from URL Content Type and choose 'GET DATA' from Type
- Section 'Get Data' will show up with number input field Size
- Any non numeric character can be entered in Size, for example '30MB'. Since that is invalid number, field Size and value don't show up in the json display.
- In the fixed version, only '30' can be entered in the Size field and so the entry is valid and will show up in the json display.
Number fields in this fixed version will accept number, …
=> MMT-3794: Fix number field issue for Firefox and Safari

static/src/js/components/CustomSelectWidget/CustomSelectWidget.jsx, static/src/js/components/GridRow/GridRow.jsx, static/src/js/schemas/uiSchemas/collections/collectionInformation.js
During SIT testing, Scott found an issue where with All Documented DOI Types --> click on type you will see all of them but if you click on “Other” you will still see all of “All Documented DOI” Types
After debugging, found out that in CustomSelectWiget the enums that were being passed to the widget were not being updated. 
List impacted areas. 
- **Environment for testing:** local
1. Create a collection draft
2. Select one of the fields for All Documented DOI and check the Type enums
3. Select other field for DOI 
4. Check if the "Other" enum is visible
=> MMT-3766: Implement UMM-C Version 1.18.1 in MMT

static/src/js/components/GroupForm/GroupForm.jsx, static/src/js/components/GroupForm/__tests__/GroupForm.test.jsx, static/src/js/components/OrderOptionForm/OrderOptionForm.jsx, static/src/js/components/OrderOptionForm/__tests__/OrderOptionForm.test.jsx, static/src/js/components/PermissionForm/PermissionForm.jsx
Currently, validation happens only upon form submission for order option, group, and permission forms. Implement 'hasVisited' logic similar to FormNavigation to enable validation as users interact with the form fields
The solution involved the following: 1) Turning on live validation.  2) Hiding the errors for those fields not visited yet.   3) Disabling the submit button until validation passes.
Note: #2 and #3 were only implemented for the Group and OrderOption form.   For the permission form, the user was not inundated with a lot of red in the form, so no special logic was added to track has visited, I just turned on live validation.
Permissions Form
Groups Form
Order Option Form
1. Try creating a new group, as you visit the fields, live validation should happen.  The submit button …
=> MMT-3774: Added live validation to group form, order option form, and permission form.

static/src/js/components/EllipsisLink/EllipsisLink.jsx, static/src/js/pages/SearchList/SearchList.jsx, static/src/js/pages/SearchList/__tests__/SearchList.test.jsx, static/src/js/pages/SearchList/__tests__/__mocks__/searchResults.js, static/src/js/utils/__tests__/handleSort.test.js, static/src/js/utils/handleSort.js
In any search list element (Collection, Variable, Service, or Tool), there is an issue where a user cannot sort their results while a provider has been selected. This ticket fixes that so that after a user selects a provider, they can then use the descending and ascending buttons without losing that provider stipulation. 
Capture the url params before they are deleted and send provider down to function. 
SearchList and tests. Fixed a few other minor issues along the way. 
- **Environment for testing: local or sit, just need published records for all concepts
1. Under Collections select 'All Collections'
2. select a Provider
3. click the up and down arrows for each column header and notice that it only sorts those with the selected provider
Screenshots …
=> MMT-3823: As a user, I want to filter my search results after choosing a provider without loosing my original search results

static/src/js/components/KeywordPicker/KeywordPicker.jsx, static/src/js/components/KeywordPicker/__tests__/KeywordPicker.test.jsx
Currently in production, we have always been able to add a higher level keyword even if child keywords exist. For example: EARTH SCIENCE SERVICES > DATA MANAGEMENT/DATA HANDLING > DATA CUSTOMIZATION can be curated as-is in production. In UAT, I am unable to add this keyword. It looks like I need to add one of its child keywords, INTERPOLATION, REPROJECTION, RESAMPLING. Currently our tools catalog uses CUSTOMIZATION as a filter option.
Removed the disabled button and let the user add a keywords at any given level
=> MMT-3839: Add support for Science Keyword Picker to add a higher level keyword even if child keywords exist

static/src/js/components/OrderOptionList/OrderOptionList.jsx, static/src/js/components/OrderOptionList/__tests__/OrderOptionList.test.jsx
When users were paginating through order options, it would throw an error on page 2. Turns out that page 2 had an order option on it from a provider called ETIM22 which is not available to the public. It was decided to create the functionality to ONLY see order options from providers that a user had access to (as seen under their profile). 
I utilized useAvailableProviders() to grab the available providers and passed that array of providerIds into the existing GET_ORDER_OPTIONS query. 
OrderOptionList.jsx
1. Set up your local environment for sit testing. If you are getting an internal error 500 let me know as I have a doc on how to fix this now. 
2. Go to your user profile and select 'providers' to take note of your …
=> MMT-3845: Error message when paginating through Order Options

static/src/js/components/GroupForm/GroupForm.jsx, static/src/js/components/GroupForm/__tests__/GroupForm.test.jsx, static/src/js/components/OrderOptionForm/OrderOptionForm.jsx, static/src/js/components/OrderOptionForm/__tests__/OrderOptionForm.test.jsx, static/src/js/schemas/orderOption.js
Order options fails in Forms XML for character limit although the character limit wasn't exceeded
Also noticed that on form load, existing errors would not appear.
Updated order options schema and removed the char limits.   Also made updates to the form logic so that only "new" records have special logic where it hides the error until the field is visited.
Order Options and Groups Form.
Easiest way to test this is to use CMR graphql to ingest a order option where the form xml > 1024 characters.
It should now load into the form, not show an error, and allow you to publish a order option with a length more than 1024 characters.
To test the other bug fix, upload an order option where the name is > 85 characters directly via CMR graphql.  When the form comes up, you should see an error. …
=> MMT-3848: Order options fails in Forms XML for character limit although the character limit wasn't exceeded

package-lock.json, package.json
MMT React Vulnerabilities Reported by Snyk (high & fixable) on July 18, 2024
CWE-1333: fast-xml-parser
CWE-1333: micromatch
https://app.snyk.io/org/esdis-cumulus-core-gibs-cmr-etc./project/74c1d039-9245-4c53-8786- e8cd1c1713d0
**Can't upgrade fast-xml-parser@3.31.1**, it is a dependency of s3rver and currently we have s3rvere@3.7.1 WHICH IS ALREADY A LATEST VERSION
serverless-s3-local@0.8.4 --> is the latest version
NOTHING BREAK --> ALL TEST PASS
Affect versions of fast-xml-parser, and micromatch packages are vulnerable to Regular Expression Denial of Service (ReDoS)
- **Environment for testing:** React local Env
BEFORE THE FIX -->Currently there are 28 vul
On branch MMT-3390
Run npm audit
Note that dicer, request, tough-cookie, and elliptic vulnerabilities …
=> MMT- 3831: MMT React Vulnerabilities July 2024

static/src/js/components/CollectionAssociationForm/CollectionAssociationForm.jsx, static/src/js/components/CollectionAssociationForm/__tests__/CollectionAssociationForm.test.jsx, static/src/js/components/CollectionAssociationForm/__tests__/__mocks__/CollectionAssociationResults.js, static/src/js/operations/mutations/createAssociation.js, static/src/js/pages/CollectionAssociationFormPage/CollectionAssociationFormPage.jsx, static/src/js/pages/OrderOptionPage/OrderOptionPage.jsx, static/src/js/schemas/collectionAssociation.js, static/src/js/schemas/uiSchemas/CollectionAssociation.js
As a user I want to be able to supply a service when associating a collection and order option
When associating a collection to an order option, for the association page, I've:
1.  Added a services combo box (see screenshot)
2.  Updated the mutation to associate the service with the collection and include the order option data as associated data, i.e., something like this:
`{
"conceptId": "S1200245793-EDF_OPS",
"associatedConceptData": [{"concept_id": "C1000000719-EDF_OPS", "data": {"order_option": "OO1200456347-EDF_OPS"}}]
}`
3.  Route the user back to the order option page after the associated is created.   If the user would like to see the assoc, they will need to go to Collection page, then click See associations (see MMT-3872 being worked now).
Collection Association Form
1. Click on …
=> Mmt 3870: As a user I want to be able to supply a service when associating a collection and order option

static/src/js/App.jsx, static/src/js/components/CollectionAssociationForm/CollectionAssociationForm.jsx, static/src/js/components/ManageServiceAssociations/ManageServiceAssociations.jsx, static/src/js/components/ManageServiceAssociations/__tests__/ManageServiceAssociations.test.jsx, static/src/js/components/ManageServiceAssociations/__tests__/__mocks__/serviceAssociationsResponses.js, static/src/js/components/PublishPreview/PublishPreview.jsx, static/src/js/components/PublishPreview/__tests__/PublishPreview.test.jsx, static/src/js/components/PublishPreview/__tests__/__mocks__/publishPreview.js, static/src/js/operations/queries/getServiceAssociations.js, static/src/js/pages/ManageCollectionAssociationPage/ManageCollectionAssociationPage.jsx, static/src/js/pages/ManageServiceAssociationsPage/ManageServiceAssociationsPage.jsx, static/src/js/pages/ManageServiceAssociationsPage/__tests__/ManageServiceAssociationsPage.test.jsx
We need to create a feature in react that allows a user to go to a published Collection Preview, click on the three dots, select 'View Services' and get redirected to a table similar to the the one attached. This table will also show any order options associated as well. PLEASE NOTE: Only one order option can be associated with a service
Added View Services to collection preview and created landing page
List impacted areas.
App.jsx
PublishPreview.jsx
- **Environment for testing: local
- **Collection to test with: Need to associated a service with an order option and a service without an order option to a single collection
1. Go to collection preview and click 'View Services' the badge next to view services should give you the service list count
2. Once on the landing page test out the …
=> MMT-3872: As a user, I would like to view all services associated with a single collection

static/src/js/components/CollectionAssociationForm/CollectionAssociationForm.jsx, static/src/js/components/CollectionAssociationForm/__tests__/CollectionAssociationForm.test.jsx, static/src/js/components/CollectionAssociationForm/__tests__/__mocks__/CollectionAssociationResults.js
The page size for retrieving services was only set to 20 when associate a service to an order option and collection.   This needs to be bumped up to 2000.
Bumped up the page size to 2000.
Association service with an order option and collections.
You should now see more than 20 services when opening up the combo when you try to supply a service when associating a order option with a set of collections.
=> MMT-3879: Updated page size to 2000.

spec/controllers/saml_controller_spec.rb
rexml library was updated in the last gem update.   This resulted in a broken test.
Fixed the test by properly giving it a valid xml string.
Bamboo, tests should pass now.
Verify we get a green build in bamboo.
Brief regression testing of MMT in SIT would be helpful too.
=> MMT-3868: Fixed test that failed do to upgrade of rexml

static/src/js/components/OrderOptionForm/OrderOptionForm.jsx, static/src/js/components/OrderOptionForm/__tests__/OrderOptionForm.test.jsx
User reported that when updating an Order Option it was being stored under a different provider than the original form is associated with.
Getting the provider ID from the CMR response and setting that when submitting.
=> MMT-3884: Edits to Order Option forms are being made under a different provider than the original form is associated with

static/src/js/components/ErrorBanner/ErrorBanner.jsx, static/src/js/components/ErrorBanner/__tests__/ErrorBanner.test.jsx, static/src/js/components/ErrorBoundary/ErrorBoundary.jsx, static/src/js/components/PublishPreview/PublishPreview.jsx
When I try to clone a collection and edit, I get the following error (see attached screen shot for details). 
Sorry! Cannot destructure property 'nativeId' of 'Tr' as it is null. See the collection record: 
https://mmt.uat.earthdatacloud.nasa.gov/drafts/collections/CD1269208926-MMT_2 
There are three use cases I'm trying to solve with this:
1. Render the old banner when appropriate 
2. Render an error banner that says "Sorry, the record does not exist" instead of 'Cannot deconstruct 'granules' of 'Cr' as draft is null.' when a record doesn't exist (this is based on the currentURL)
3. Render a prompt that tells users to refresh the page if they've come from trying to clone or edit a published record (this is based on the previousURL)
ErrorBanner, ErrorBoundary, and PublishPreview
- …
=> MMT-3877: Cloning bug fix

static/src/js/components/DraftPreview/DraftPreview.jsx, static/src/js/components/ErrorBanner/ErrorBanner.jsx, static/src/js/components/ErrorBanner/__tests__/ErrorBanner.test.jsx, static/src/js/components/ErrorBoundary/ErrorBoundary.jsx, static/src/js/components/Layout/Layout.jsx, static/src/js/components/PublishPreview/PublishPreview.jsx, static/src/js/pages/DraftPage/DraftPage.jsx
Errors occur during two particular use cases:
Collections >> Collection >> Clone >> 'Cannot destructure property \'nativeId\' of \'Tr\' as it is null.' (this error comes from DraftPage.jsx line 90 when MMT tries to ask for the draft but the draft doesn't exist in CMR yet)
Collections >> Collection >> Clone >> Edit >> Save & Publish >> 'Cannot destructure property \'granules\' of \'Cr\' as it is null.' (this error comes from PublishPreview.jsx line 101 when MMT tries to ask for the published record but it doesn't exist in CMR yet) 
Please summarize the feature or fix.
Initially, the thought was that we should use useHistory for this bug. If a user is coming from publishpreview or is coming from draftpage, then render a refresh banner. But there are two issues with this:
1) useHistory is …
=> Mmt 3877b: Error When Cloning and Editing a Draft Collection

static/src/js/components/CollectionSelector/CollectionSelector.jsx, static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx, static/src/js/components/PermissionForm/PermissionForm.jsx, static/src/js/components/PermissionForm/__tests__/PermissionForm.test.jsx, static/src/js/operations/queries/getCollectionForPermissionForm.js
There is a bug in the PermissionForm where it would only load the first 20 selected collections, even though the user may have had 100s.   As a result, when the user saved the permission form, it would only save the first 20 resulting in the rest of the collections be removed from the ACL.
As a temporary solution, I've bumped up the limit parameter to graphql to pull up to 2000 collections.   I've also bumped up the available collections limit to 100, as users where stating that 20 was not large enough list size, due to some searches by short name having more than 20.
A permanent solution to this ticket will be to support more than 2000 selected collections but will require a bit more work.   Also the users would like the search within available collections to be more than just short …
=> SAP-129: Saving Collection Permissions ACLs is removing all but 20 selected collections

static/src/js/components/ManageCollectionAssociation/ManageCollectionAssociation.jsx, static/src/js/components/ManageCollectionAssociation/__tests__/ManageCollectionAssociation.test.jsx, static/src/js/components/ManageCollectionAssociation/__tests__/__mocks__/manageCollectionAssociationResults.js
Users could not paginate through Collection Association Results
Adding Pagination
ManageCollectionAssociation.jsx
- **Environment for testing: Find a Service with more than 20 Associations or do the associations yourself. The one I'm using in UAT is here: /services/S1226158232-MMT_1/collection-association
1. Select a service >> go to Collection Associations >> check that you can paginate through associations
=> Mmt 3902: As a user, I would like to paginate through my collection associations

static/src/js/App.jsx, static/src/js/components/CollectionSelector/CollectionSelector.jsx, static/src/js/components/CollectionSelector/__tests__/CollectionSelector.test.jsx, static/src/js/components/Layout/Layout.jsx, static/src/js/components/Layout/__tests__/Layout.test.jsx, static/src/js/components/PermissionForm/PermissionForm.jsx, static/src/js/components/PermissionForm/__tests__/PermissionForm.test.jsx, static/src/js/operations/queries/getCollectionForPermissionForm.js
A user reported that its primary access policy that exposes > 800 collections in ops was reduced to only 20 collections after a update the ACL.
The selected collections pane was only retrieving 20 collections, even though the ACL could have many more.   Therefore, when the ACL was updated, it would only update with the 20 collections it retrieved and not the full list of collections in the ACL.
The solution is to use fetchMore provided by Apollo to request all the collections in the ACL.  
The collection permissions page.
Try finding a ACL that has over 20 collections (or create a ACL that includes more than 20).   Verify you can add and remove collections.   Verify all collections you add show up in the right pane and the submit works properly with your additions and subtractions.
=> MMT-3895: Now pulls in ALL selected collections.

package-lock.json
MMT React Vulnerabilities September 2024
Run npm audit fix to fix the vulnerabilites that can be fixed. 
NOTE: Neither dicer nor fast-xml-parser vulnerabilites can be fixed. It says 'fix available' but that will bump the version down to an older version that will cause issues. At the moment, both dicer and fast-xml-parser issues are dependants of serverless-s3-local which is already at the latest version see here: https://www.npmjs.com/package/serverless-s3-local/v/0.8.5 so no fix if available for our two high vulnerabilites
package-lock.json
- **Environment for testing: N/A
1. On main branch run npm audit and see>> 15 vulnerabilities (7 moderate, 8 high)
2. On MMT-3882 branch run npm audit and see>> 7 vulnerabilities (3 moderate, 4 high)
=> Mmt 3882: MMT React Vulnerabilities September 2024

static/src/js/components/ManageCollectionAssociation/ManageCollectionAssociation.jsx, static/src/js/components/PermissionCollectionTable/PermissionCollectionTable.jsx, static/src/js/components/PermissionCollectionTable/__tests__/PermissionCollectionTable.test.jsx, static/src/js/components/PermissionCollectionTable/__tests__/__mocks__/permissionCollectionTableResults.js
Needed to add pagination to /permssions/conceptId and the collection table
Added pagination
PermissionCollectionTable.jsx
- **Environment for testing: Any
1. Select an ACL and check pagiantion for three use cases: all collections permitted, less than 20 collections permitted, more than 20 collections permitted.
=> MMT-3908: Adding pagination to ACL

static/src/js/components/MetadataPreview/__tests__/MetadataPreivew.test.jsx, static/src/js/components/MetadataPreview/__tests__/__mocks__/MatadataPreviewMocks.js, static/src/js/operations/queries/getCollectionDraft.js
Collection draft preview doesn't display title after short name
In graphql query use entryTitle value for title
Collection draft preview
Collection draft preview should show title after short name
N/A
=> MMT-3910: Use entryTitle to display title in collection draft preview

static/src/js/components/CustomCountrySelectWidget/CustomCountrySelectWidget.jsx, static/src/js/components/CustomCountrySelectWidget/__tests__/CustomCountrySelectWidget.test.jsx
Existing country in address form doesn't displayed in the draft form and only short form of country names are written to json.
Issues were that Country selector:
1. When it writes to json, the short form of the country name is written ('US' instead of 'United States', 'TZ' instead of 'Tanzania, United Republic of')
2. When importing into the form (Edit a Collection), values like 'United States' in address field 'Country' will not be displayed in the form.
3. 
Those issues are fixed:
1. Long form of country name is to be written to json.
2. When edit an existing record, both short and long form of country name will be read and displayed. 
List impacted areas.
Country selector
1. Create a new draft, long form of country name is written out to json.
2. Import an existing collection with 'US' …
=> MMT-3891: Existing country should be displayed in draft form.

static/src/js/pages/DraftPage/DraftPage.jsx, static/src/js/pages/DraftPage/__tests__/DraftPage.test.jsx
There was an influx of users trying to publish drafts to CMR, when they clicked published there was no indication of whether or not the published work.  In the cases mentioned, CMR failed to push and the user had no idea.
We should capture any errors during publish and present any errors if there are problems.
The hook provides errors, so I added a useEffect to capture any changes and now presenting them to the user.
Publishing a draft.
This is easier to test before GQL-75 gets merged, as there are a number of records that won't publish due to the native id including special characters.   So you should be able to ingest a record where the native id has '/' in it and try publishing with MMT, it should not work and now MMT will show an error to the UI.
=> MMT-3915: Fixed when a user tries to publish a draft and is unsuccessful, there is no error message displayed

package-lock.json, package.json
There is no way to test ECHOACCESS-229 in MMT SIT until this version number is bumped
Bump version number to match most recent version release here: https://www.npmjs.com/package/@edsc/metadata-preview
List impacted areas.
1. Just double check this works in your local environment
=> Mmt-3916: Bumping @edsc/metadata-preview version to match for ECHOACCESS-229 testing

static/src/js/components/PermissionForm/PermissionForm.jsx, static/src/js/schemas/collectionPermission.js, static/src/js/schemas/uiSchemas/collectionPermission.js
The provider combo box should not allow someone to change the ACL's provider on updating the ACL.   
If the user is updating the ACL (i.e., adding/removing collections and other updates), the provider combo box should be disabled.
If the user is creating a new ACL, it should be enabled.
ACL permissions creation and updating.
Verify that when updating ACL permissions, the provider combo box is disabled.
Verify that when creating ACL permissions, the provider combo box is enabled.
=> MMT-3907: Updated provider dropdown so it is disabled on updating the ACL.   Only creation of the ACL will it be enabled.

static/src/js/components/DraftPreview/DraftPreview.jsx, static/src/js/components/DraftPreview/__tests__/DraftPreview.test.jsx, static/src/js/pages/DraftPage/DraftPage.jsx, static/src/js/pages/DraftPage/__tests__/DraftPage.test.jsx
There is a special use case where users are clicking 'delete' and their drafts are not deleting. It has been determined that the issue is that CMR is returning drafts that do no exist to the concept draft list (this is necessary to render list of drafts and will be fixed by https://bugs.earthdata.nasa.gov/browse/CMR-10190. 
If users click into a draft with this special error case, they will be directed to page with disabled buttons and text reading that the draft does not exist.
DraftPreview and DraftPage
- **Collection to test with: http://localhost:5173/drafts/collections/CD1200483643-MMT_2
1. Go to link above and see new text
2. Go to any other draft and ensure all other works
=> MMT-3906: Error deleting Drafts in MMT

static/src/js/components/InstrumentField/InstrumentField.jsx, static/src/js/components/InstrumentField/InstrumentField.scss, static/src/js/components/InstrumentField/__tests__/InstrumentField.test.jsx, static/src/js/schemas/uiSchemas/collections/acquisitionInformation.jsx, static/src/js/utils/__tests__/parseCmrInstrumentsResponse.test.js, static/src/js/utils/parseCmrInstrumentsResponse.js
Duplicated instrument name causes the issue that no long name shows up in json view.
Use type, subtype and short name to create key for long name map. Add title and tooltip to select box entries to ease selection of duplicated instrument names. 
Instrument list and 'Composed Of' in Platforms (Acquisition Information)
Instrument list should show titles to group entries in the select box and each entry has a tooltip which shows type>subtype 
N/A
=> MMT-3912: Instrument Long Name not populate in the JSON when populated in MMT Forms

static/src/js/schemas/uiSchemas/collections/spatialInformation.jsx, static/src/js/utils/__tests__/parseCmrResponse.test.js
keyword pickers do not allow for searching below the Continent level hierarchy and add keywords such as countries or US States
Column names of sub regions were wrong in the ui schema file, now fixed.
Location keywords picker in 'Spatial Information'
See test session.
N/A
=> MMT-3914: Not Allowing Certain GCMD Location Keywords to be Added

static/src/js/components/MetadataForm/MetadataForm.jsx, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.jsx, static/src/js/providers/AppContextProvider/AppContextProvider.jsx, static/src/js/utils/__tests__/checkForCMRFetchDraftLag.test.js, static/src/js/utils/checkForCMRFetchDraftLag.js
When users would click Save & Continue, occationaly an incorrect version of the draft would populate. This code triggers a useEffect if the revisionId that comes back from CMR does not match the revisionId that we expect. 
Add revisionId to AppContextProvider and set it when a user ingests a draft. This triggers a change in the data which triggers a fetchdraft useeffect. 
MetadataForm and AppContextProvider
- **Environment for testing: UAT
- **Collection to test with: Any new draft
1. Insert the following below line 144 in MetadataForm.jsx in order to see what's going on in the useEffect:
console.log("🚀 ~ useEffect ~ cmrRetrievedRevisionId:", cmrRetrievedRevisionId)
console.log("🚀 ~ useEffect ~ appContextRevisionId:", appContextRevisionId)
3. Create a new draft and click Save & Continue. …
=> Mmt 3922: User is experiencing an issue with MMT deleting information added even after hitting "Save and Continue."

static/src/js/components/Notifications/Notifications.jsx, static/src/js/components/Notifications/__tests__/Notifications.test.jsx
Goes along with GQL-87. Now that users are receiving cmr errors, they need to be able to read them. Currently, they are showing up and then autohiding after 4 seconds. 
Error notification with better messages from CMR stay present until user clicks 'close'
Notifications.jsx
- **Environment for testing: local
- **Collection to test with: you own
Create a local collection draft that is ready to publish. Ensure that it does publish then go back to edit.
Under Aquisitional Information, create two ComposedOfs with the same shortName.
If doing this in graphQL, you should see it return with this message: ""message": "Location: Platforms[0] > Instruments[0] > ComposedOf,Composed Of must be unique. This contains duplicates named [ATM]." In MMT, you should get three notifications pop up: one that …
=> Mmt 3934: CMR Publish Operation Error Not Surfaced to User

static/src/js/components/Permission/Permission.jsx, static/src/js/components/Permission/__tests__/Permission.test.jsx
MMT displays invalid group permissions, which show up with empty group name in the UI.
Remove invalid group permissions so they don't show up.
Single permission view.
See test session
See ticket.
=> MMT-3919: Remove invalid group permissions

static/src/js/components/RevisionList/RevisionList.jsx, static/src/js/components/RevisionList/__tests__/RevisionList.test.jsx, static/src/js/components/RevisionList/__tests__/__mocks__/revisionResults.js
Bug: Current UI for RevisionList does not indicate to user that a revision has been deleted. Created UI for deleted rows as a temp fix. 
when userId === 'cmr' consider the row deleted. 
RevisionList.jsx
- **Environment for testing: UAT
- **Collection to test with: http://localhost:5173/variables/V1256589611-MMT_2/revisions
1. Check out the revisions for above Variable. You should see that the row shows that it has been deleted and is unactionable.
=> MMT-3946: Bug: Current UI for RevisionList does not indicate to user that a revision has been deleted

package-lock.json, package.json, static/src/js/components/CustomDateTimeWidget/CustomDateTimeWidget.jsx, static/src/js/components/CustomDateTimeWidget/__tests__/CustomDateTimeWidget.test.jsx, static/src/js/components/RevisionList/RevisionList.jsx, static/src/js/components/RevisionList/__tests__/RevisionList.test.jsx, static/src/js/components/RevisionList/__tests__/__mocks__/revisionResults.js
The existing date/time widget would wipe out any time the user selected.   We should allow them to select a time or type in the time and preserve what they type.
The widget now configures the react-date-picker to show times.   Also if they select a time, it should display in ISO format.   Both the time picker and the text field should show the date in UTC.
Any forms that use the date time picker (such as Temporal Information page)
Go to the Temporal Information page and add a Single Date Time.   Click on the text field, this will bring up the widget.
You'll see the ability to select times on the right.  
You can also type in the time in the text box.
Verify that either what you select or type show up in the JSON below.
=> MMT-3943: Updated to support times in UTC

bin/download_schemas.sh
MMT should pull down schemas from respective cdn env sit, uat or prod
Download schema script should read $bamboo_STAGE_NAME to build the cdn url.
Deployment
Schema files downloaded and deployed.
N/A
=> MMT-3876: MMT should pull down schemas from respective cdn env

static/src/js/components/CustomCheckboxWidget/CustomCheckboxWidget.jsx, static/src/js/components/CustomCheckboxWidget/__tests__/CustomCheckboxWidget.test.jsx, static/src/js/schemas/uiSchemas/collectionPermission.js
The Access Constraint Filter value edit boxes require values, when they are actually optional.   This happens when you click "Include undefined", but if you uncheck it, it never resets the edit boxes to say min/max values are no longer required.   The reason is the way the schema works, clicking the checkbox sets a true/false value for the field.   If that field exists, then it makes the other fields required as well.   
Added a "ui:clearUndefined" to the CustomCheckboxWidget and set this value in the uiSchema for these checkboxes only, default behavior is false as normal.   But if set to true (which this ui schema does), it will propogate up a null instead.   This wil tell the form, this field should be cleared out.   Once that that happens, the required field message disappear because …
=> MMT-3935: Fix Invalid Access Constraint Definition UI Errors

static/src/js/components/KeywordPicker/KeywordPicker.jsx, static/src/js/components/KeywordPicker/__tests__/KeywordPicker.test.jsx
Science Keyword Picker Adds An Additional Science Keyword That Was Not Originally Selected
In the onChange event, check if the text to search is empty, if so, ignore the search.
Science Keyword Picker
Here are the steps to reproduce (video demonstration is also attached). 
Navigate to a collection > Descriptive Keywords
Search for a keyword using the keyword widget
Add a keyword
Click x in the search picker
EARTH SCIENCE > AGRICULTURE > AGRICULTURAL AQUATIC SCIENCES > AQUACULTURE is added by mistake (note: this is the 1st keyword in the keyword pick list.)
=> MMT-3926: Fix for Science Keyword Picker Adds An Additional Science Keyword That Was Not Originally Selected

static/src/js/components/ErrorBoundary/ErrorBoundary.jsx, static/src/js/components/ErrorBoundary/__tests__/ErrorBoundary.test.jsx
cmr-graphql returns intermittent error getting acl and groups from EDL.
Catch that error and create banner message to refresh browser. 
View of single Permission
See test session.
N/A
=> MMT-3923: Catch intermittent error from EDL

static/src/js/components/MetadataForm/MetadataForm.jsx, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.jsx
The "Save and Publish" menu option is causing an issue where the user is encountering a latency error mesage after clicking this option.   This happens every time.
When the save and publish updates the draft, there is a use effect that verifies that the revision id saved matches what is in the url after the save.   The issue was that the URL was not being updated in between the time the save happened and the publish navigating away from the page.   The fix was simply to include the navigate to update the page revision id while publishing.
Metadata Form menu navigate menu options.
Create a draft, fill in all the required fields, click Save.   The click Save and Publish.   The draft should now properly redirect to the preview page without any errors.
=> MMT-3953: Fix for User is encountering latency issue with Save and Publish

static/src/js/components/CustomDateTimeWidget/CustomDateTimeWidget.jsx, static/src/js/components/CustomDateTimeWidget/__tests__/CustomDateTimeWidget.test.jsx
Millisecond part of date time input should accept input values.
Preserve input values of millisecond part and reset it only when date time value is selected.   
All date time fields.
1. Existing temporal extends should be preserved when loaded into the form.
2. Copy and pasted values should be preserved.
3. Selected values from the widget should have the millisecond part set to 0.
N/A
=> MMT-3960: Resetting millisecond part only when date time is selected.

sharedUtils/__tests__/getConfig.test.js, static.config.json, static/src/js/components/MetadataPreview/MetadataPreview.jsx, static/src/js/components/MetadataPreview/__tests__/MetadataPreview.test.jsx, static/src/js/components/MetadataPreview/__tests__/__mocks__/MatadataPreviewMocks.js, static/src/js/operations/queries/getCollection.js
This collection has over 20 associated variables: 
https://access.sit.earthdata.nasa.gov/collections/C1200268821-EDF_DEV01
https://mmt.sit.earthdata.nasa.gov/collections/C1200268821-EDF_DEV01
You'll noticed that the associated variables look different in mmt vs in access. Access works as it should while MMT only pulls the first 20 associated variables and then starts a list of all variables from the beginning. 
The call getCollections needed to mimic what was happening with edsc-cmr-preview. Added variableParams so that it changes the limit from 20 to 1000.
ALSO made minor change to adjust for new localhost setup in static.config and config test file. 
MetadataPreview
- **Collection to test with: C1200277732-EDF_DEV01
1. Spin up mmt react and let Mandy …
=> MMT-3961: As a user, I can view a list of associated variables for a collection when the associated variables count is >20

serverless/src/samlCallback/handler.js, serverless/src/utils/__tests__/fetchEdlProfile.test.js, serverless/src/utils/fetchEdlProfile.js
This PR just reverts my previous commits of console log statements to help debug why users couldn't login.
Used git revert to revert the last commit
SAML callback handler.
Basic regression testing.
=> Revert "MMT-3962: Added console log statements to help debug issue with login. (#1336)"

static/src/js/operations/queries/getCollection.js, static/src/js/pages/ManageCollectionAssociationPage/__tests__/__mocks__/collectionResult.js, static/src/js/pages/RevisionListPage/__tests__/__mocks__/searchResults.js
While at first glance it appeared this issue had been resolved, if you go to page 2 of Associated Variables in mmt here https://mmt.sit.earthdata.nasa.gov/collections/C1200277732-EDF_DEV01, you'll notice it is different from the same page here https://access.sit.earthdata.nasa.gov/collections/C1200277732-EDF_DEV01
getCollection wasn't asking for AssociationDetails which is needed for the function to work properly in Access. 
getCollection call
- **Collection to test with: C1200277732-EDF_DEV01
1. Run this collection in your local SIT environment (you'll need to comment out related Collections in getCollection to get the environment working)
2. Go to both pages in AssociatedVariables and make sure that the variables line up with what's in access. The two …
=> MMT-3961b: Adding AssociatedDetails

package-lock.json
Was this: 22 vulnerabilities (1 low, 16 moderate, 5 high)
Now it is this: 15 vulnerabilities (1 low, 11 moderate, 3 high)
Fixed these:
@babel/helpers  <7.26.10
Severity: moderate
Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
fix available via `npm audit fix`
node_modules/@babel/helpers
@babel/runtime  <7.26.10
Severity: moderate
Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
fix available via `npm audit fix`
node_modules/@babel/runtime
axios  <1.8.2
Severity: high
axios Requests Vulnerable To Possible SSRF and Credential Leakage via Absolute URL - …
=> MMT-3973: March Vulnerabilites

app/views/shared/_footer.html.erb, spec/vcr/edl/approver_workflow_spec_vcr.yml
The nasa official listed on dMMT earthdata sites is Stephen Berrick, we need to update these to be Doug Newman.
Swapped out names in footer and approver workflow
1. Spin up local environment and see that change has been made.
=> MMT-3970: Update the "NASA Official" footers on all dMMT pages to be Doug Newman

static/src/js/components/AboutModal/AboutModal.jsx, static/src/js/components/Footer/Footer.jsx, static/src/js/components/Footer/__tests__/Footer.test.jsx, static/src/js/schemas/umm/ummCSchema.js
The nasa official listed on MMT earthdata sites is Stephen Berrick, we need to update these to be Doug Newman.
Changed in footer and About Modal
Footer and About Modal
1. Spin up local environment to see changes on footer before authorizing yourself.
2. Once signed in, click on your name in the bottom left of the screen the select 'About' to see where other change needed to be made
=> MMT-3969: Update the "NASA Official" footers on all MMT pages to be Doug Newman

package.json, yarn.lock
rake assets:precompile was failing with message:
COMPILATION FAILED:
EXIT STATUS: pid 53587 exit 2
OUTPUTS:
[webpack-cli] Failed to load '/Users/cgokey/Developer/rails/mmt/config/webpack/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'shakapacker'
Require stack:
For whatever reason shakapacker was in dev deps and needed to be in regular reps.
dMMT deployments
Should be able to hit https://draftmmt.sit.earthdata.nasa.gov
=> MMT-3970: Updates to deploy with assets.

.eslintrc, bin/deploy-bamboo.sh, jsconfig.json, package-lock.json, static.config.json, static/src/js/App.jsx, static/src/js/__tests__/App.test.jsx, static/src/js/components/Layout/Layout.jsx, static/src/js/components/Layout/__tests__/Layout.test.jsx, static/src/js/hooks/__tests__/usePermissions.test.jsx, static/src/js/hooks/usePermissions.js, static/src/js/operations/queries/getPermissions.js, static/src/js/pages/KeywordManagerPage/KeywordManagerPage.jsx, static/src/js/pages/KeywordManagerPage/__tests__/KeywordManagerPage.test.jsx, vite.config.js
Authorized users can access the Keyword Manager underneath the Admin header.
Under Admin, there is now a tab for Keyword Manager. This tab is only visible to users with access to the Keyword Manager. At the moment, the permission endpoint for this is awaiting creating with CMR-10495. For now, we are using the Group permission to test this. 
Navigations and new Keyword Manager landing page
1. Point local environment to SIT and log on. 
2. Under usePermissions.js, change line 30 to 'GROUP'. (change back to KEYWORDS before running tests)
3. Load page and see that Keyword Manager is accessible under Admin. 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the …
=> MMT-4010: As a user, I can navigate to a landing page for Keyword Manager.

bin/deploy-bamboo.sh, static.config.json, static/src/js/components/SystemPermissions/__tests__/SystemPermissions.test.jsx, static/src/js/constants/systemIdentityPermissions.js, static/src/js/hooks/__tests__/usePermissions.test.jsx, static/src/js/hooks/usePermissions.js
To pull this down, please use MMT-41010b. Sorry! 
In the previous ticket, I didn't have the ACL. Now that I do, I'm resubmitting this again with the actual ACL.
Swapped out dummy data for the real thing and removed feature toggle.
usePermissions and systemIdentityPermissions
1. Go to System Groups under Admin and select Administrators. Under Administrators, look for Keyword Management System and toggle the permissions. You should see that the Keyword Manager appears and disappears when you toggle that permission. 
=> MMT-4010b: Adding in real ACL - As a user, I can navigate to a landing page for Keyword Manager.

static.config.json, static/src/js/components/DraftList/DraftList.jsx, static/src/js/components/DraftList/__tests__/DraftList.test.jsx, static/src/js/components/DraftList/__tests__/__mocks__/DraftListMocks.js, static/src/js/components/Layout/Layout.jsx, static/src/js/components/Layout/__tests__/Layout.test.jsx, static/src/js/constants/conceptTypeDraftsQueries.js, static/src/js/constants/conceptTypeQueries.js, static/src/js/constants/conceptTypes.js, static/src/js/constants/redirectsMap/redirectsMap.js, static/src/js/constants/typeParamToHumanizedStringMap.js, static/src/js/constants/urlValueToConceptStringMap.js, static/src/js/operations/queries/getVisualizationDrafts.js, static/src/js/operations/queries/getVisualizations.js, static/src/js/pages/SearchList/SearchList.jsx, static/src/js/pages/SearchList/__tests__/SearchList.test.jsx, static/src/js/pages/SearchList/__tests__/__mocks__/searchResults.js, static/src/js/pages/SearchPage/SearchPage.jsx
Users can navigate to a list of published visualizations
Users can navigate to a list of draft visualizations
Created a new navigation header and subheaders for Visualizations
**NOTE that the search bar and the long name sorting have been removed. These are not currently supported and we need to wait on CMR to get those fixed. There is a separate ticket to take care of these. 
SearchList and DraftList
1. Spin up branch and see that the new navigation headers are there and that the page loads as expected. Pagination should work as expected. 
=> MMT-3990: Adding Published and Draft Visualizations

static/src/js/components/KeywordTree/KeywordTree.jsx, static/src/js/components/KeywordTree/__tests__/KeywordTree.test.jsx, static/src/js/pages/KeywordManagerPage/KeywordManagerPage.jsx, static/src/js/pages/KeywordManagerPage/__tests__/KeywordManagerPage.test.jsx
User can add new narrower keyword
Add new context menu item 'Add Narrower' to add new keyword.
The keyword tree and the form. The form will show the new keyword's detail for user to edit.
Right click on a keyword on the tree, click 'Add Narrower', new keyword should show up in the form.
N/A
=> MMT-4006: User can add new narrower keyword

static/src/js/operations/queries/getVisualization.js, static/src/js/operations/queries/getVisualizationDraft.js
GQL had a change to field where temporalExtent became temporalExtents. Made that change here so that MMT-3991 can be fully tested
adding an s
visualization queries
1. Spin up environment and make sure that we can make calls to published and draft visualization
N/A
- [] I have made corresponding changes to the documentation
=> MMT-3991b: Updating temporalExtent to Temporal Extents for the graphql visualization query

package-lock.json, package.json, setup/setupCmr.js, static/src/js/components/MetadataPreview/MetadataPreview.jsx, static/src/js/components/MetadataPreview/__tests__/MetadataPreview.test.jsx, static/src/js/components/MetadataPreview/__tests__/__mocks__/MatadataPreviewMocks.js, static/src/js/operations/queries/getCollection.js, static/src/js/operations/queries/getVisualization.js, static/src/js/operations/queries/getVisualizationDraft.js, static/src/js/operations/queries/getVisualizationDrafts.js
This adds the most recent version of `cmr-preview` so that we can preview umm-vis records
Updating the package deps to include this updated version, updating the graphql query and adding the visualization preview component
I bumped express to satisfy a PR that dependabot was making and I ran npm audit fix.
Some of the tests on main were throwing apollo errors this fixes that as well
Package dependencies, MMT's preview page for Visualization records and collection records
- **Environment for testing:*Local*
- **Collection to test with:*NA*
1. Create a umm-vis record ingest it into your local CMR
2. Associate a collection to that umm-vis record
3. Create a draft umm-vis record
4. Ensure that the above's preview pages are displaying correctly
5. Ensure that the association between the …
=> MMT-4000: As a user, I can see the metadata preview for Visualizations on MMT

static/src/js/hooks/usePublishMutation.js, static/src/js/schemas/otherSchemasVisSchema.js, static/src/js/schemas/uiForms/visualizationConfiguration.js, static/src/js/schemas/uiSchemas/visualizations/index.js, static/src/js/schemas/uiSchemas/visualizations/spatialExtent.jsx
Users can edit Spatial Extent
Add spatialExtent.jsx
VisualizationConfiguration and UiSchemas
- **Environment for testing:SIT
- **Collection to test with:New draft or "Created Using Form" draft
1. Go to Spatial Extent and play around with all the different checkboxes and dropdowns for fields and make sure they all look correct.
=> MMT-3996: As a user, I can edit the Spatial Extent

static/src/js/components/KeywordTree/KeywordTree.jsx, static/src/js/components/KeywordTree/__tests__/KeywordTree.test.jsx, static/src/js/components/KmsConceptSelectionEditModal/KmsConceptSelectionEditModal.jsx, static/src/js/components/KmsConceptSelectionEditModal/__tests__/KmsConceptSelectionEditModal.test.jsx, static/src/js/pages/KeywordManagerPage/KeywordManagerPage.jsx, static/src/js/pages/KeywordManagerPage/__tests__/KeywordManagerPage.test.jsx, static/src/js/schemas/uiSchemas/keywords/editKeyword.js, static/src/js/schemas/umm/keywordSchema.js, static/src/js/utils/convertFormDataToRdf.js
Tree now supports the ability to filter by a pattern search, as well as UUID.
Added a text box to the top of the tree to allow filtering the tree by pattern.   Refactored a large part of the code to put most of the logic now in KeywordTree, before it was scattered in multiple places (Keyword Page, Edit Modal, etc.).    The tree is now responsible for fetching data, now has a hook that can be called for refreshing the tree, etc.  
Main Page
Edit Modal when editing a keyword.
From the main page, try searching for a keyword and editing it.
From the form page, try editing a keyword, make sure nothing broke there.
=> MMT-4018: As a user, I can filter the navigation tree by a pattern search

static/src/js/components/GroupPermissionSelect/GroupPermissionSelect.jsx, static/src/js/components/GroupPermissionSelect/__tests__/GroupPermissionSelect.test.jsx, static/src/js/components/PermissionForm/__tests__/PermissionForm.test.jsx
Currently the initial group list is limited to 20 groups. This fix increases the initial group list to 500.
Increasing the initial group list to 500
React MMT when creating new permissions.
- **Environment for testing: SIT**
1. Use React MMT in SIT and create a new permission at https://mmt.sit.earthdata.nasa.gov/permissions/new
2. At the bottom of the page under "Group Permissions" click on one of the drop downs. Make sure it lists more than 20 options (not including "All guest users" or "All registered users"). 
=> MMT-4035: Increasing initial retrieval limit to 500 for groups

index.html
The Fed DAP script (Federal Digital Analytics Program) serves the General Services Administration (GSA), and is required for all public facing federal websites. Basically it allows federal agencies to track metrics through the GSA analytics property. It’s the same google dashboard but for all government agencies.
Add Fed DAP script to header of index.html
index.html
- **Environment for testing:local
1. Open the Network tab, remove any filters, should see a call to Universal-Analytics-Fedartion-Min.js
=> MMT-3967: Adding FED DAP code

package-lock.json, static/src/js/components/KmsConceptSelectionWidget/KmsConceptSelectionWidget.jsx, static/src/js/components/KmsConceptSelectionWidget/__tests__/KMSConceptSelectionWidget.test.jsx, static/src/js/utils/__tests__/getKmsConceptFullPaths.test.js, static/src/js/utils/getKmsConceptFullPaths.js
Widget needs to use version to fetch concept full path. Without version, getting new concept full path in draft results in error because getKmsConceptFullPaths can't find it in published version.
Pass version as parameter for kms call in getKmsConceptFullPaths.
Also fix 1 critical vulnerabilities pbkdf2 
Concept Selection Widget in keyword form.
Add a new narrower keyword. Save it. Pick another keyword to edit, choose the new keyword as broader or narrower, hit save, see attachment for error shown. Fixed version (this branch) should not show that error.
=> MMT-4048: Concept Selection Widget needs to include version when retrieving concept full path.

package-lock.json, package.json, static/src/js/components/JsonPreview/JsonPreview.jsx, static/src/js/components/JsonPreview/__tests__/JsonPreview.test.jsx, static/src/js/components/MetadataForm/MetadataForm.jsx, static/src/js/components/MetadataForm/__tests__/MetadataForm.test.jsx, static/src/js/pages/MetadataFormPage/MetadataFormPage.jsx, static/src/js/pages/MetadataFormPage/__tests__/MetadataFormPage.test.jsx
What is the bug?
User clicks Publish (not sure if it matters clicking publish from PublishPreview or MetadataForm) and should be redirected to /concept/conceptId
Instead, user is redirected to /drafts/concept/conceptId which calls getConceptDraft which is looking for previewMetadata. However, when a user clicks publish, that triggers the draft to be deleted, so users are trying to query for a draft that no longer exists.
Take out the || statement from earlier save option and put an additional navigation into saveAndPublish
List impacted areas.
- **Environment for testing:SIT
- **Collection to test with:New
1. Create a new record and publish it using save&publish
=> MMT-4050: BUG FIX: When clicking publish, users may receive an intermittent error claiming previewMetadata returns null

static/src/js/schemas/otherSchemasCitSchema.js, static/src/js/schemas/uiSchemas/citations/citationMetadata.js, static/src/js/schemas/uiSchemas/citations/index.js, static/src/js/schemas/uiSchemas/citations/relatedIdentifiers.js
Update MMT to support entering related identifiers and citation metadata.
Most of the changes were just changing ui schemas.   I took a little bit of liberty with breaking out the citation details into sections just to improve the look of the form.  
Entering citation details.
Verify each form has all the fields as specified in the schema.
Verify no issues when filling out the form.
=> MMT-4054: As a user, I can enter related identifiers and citation metadata

static/src/js/constants/restoreRevisionMutations.js, static/src/js/operations/mutations/restoreCitationRevision.js
Adding ability to review past revisions of a Citation and restore a previous revision.
Adding the restore Citation Revision mutation.
MMT
View a Citation (or create a citation if none are present) Click on the 3 dots to pull the drop down and click on View Revisions. If there is only 1 Revision, then make an edit and save it so that there are multiple revisions (You can change the name so its easy to tell what changed.).
On the Revisions page, check that "Revert to this revision" is shown on the previous revisions. You can click the "Revert to this revision" link and ensure that a new Published revision gets created. Verify that the published revision is the same as the one you wanted.
Please include relevant screenshots or …
=> MMT-4055: Adding ability to restore previous Citation revisions

static/src/js/components/PublishPreview/PublishPreview.jsx, static/src/js/components/PublishPreview/__tests__/PublishPreview.test.jsx, static/src/js/components/TemplateForm/TemplateForm.jsx, static/src/js/components/TemplateForm/__tests__/TemplateForm.test.jsx, static/src/js/components/TemplatePreview/TemplatePreview.jsx, static/src/js/components/TemplatePreview/__tests__/TemplatePreview.test.jsx, static/src/js/operations/mutations/restoreVisualizationRevision.js
Adjusting toast message to include specific ingestDraftError message
Adjusting toast message to include specific ingestDraftError message
When a user doesnt have PROVIDER_CONTEXT read permissions for a provider
Ensure the user does not have PROVIDER_CONTEXT read permissions for a provider.
If you need to remove the permission, you can do so but you have to wait about 2 hours to make sure it takes affect.
View a collection for that provider.
Click the Edit button.
You should get the following toast message:
Error creating draft: You do not have PROVIDER_CONTEXT permission to perform that action.
=> MMT-4044: Adjusting error message to include message from ingestDraftError

static/src/js/components/CustomToggle/CustomToggle.jsx, static/src/js/schemas/uiSchemas/GroupSearch.js
Fixing the dropdown issue in groups after searching a second time. Also enlarging the "more actions" icon
Adjusted the z-index of the dropdown and enlarged the icon.
React MMT
Go to Groups and select a provider then select submit.
Now go to select a provider again and notice that the drop-down menu is not obscured by the table. 
Select a collection and view the more actions icon. MAke sure its size is inline with with Edit/Delete/Clone buttons
=> MMT-4069: Fixing dropdown z-index and englarging more actions icon

static/src/js/components/PermissionForm/PermissionForm.jsx
There is a useEffect race condition that can happen due to multiple useEffects updating the same form data.
The fix is to merge 3 of these useEffects into a single useEffect.
Loading of existing permission data into the form.
Try modifying a permission, saving, going back in, and repeating that multiple times.  Occasionally it will 
fail to load the fetch data due the initial form data loading over the top of it.   It doesn't happen all the time.
=> MMT-4080: Moved everything into one useEffect

package-lock.json, package.json, static/src/js/components/MetadataPreview/MetadataPreview.jsx, static/src/js/components/MetadataPreview/__tests__/MetadataPreview.test.jsx, static/src/js/components/MetadataPreview/__tests__/__mocks__/MatadataPreviewMocks.js, static/src/js/operations/queries/getCitation.js, static/src/js/operations/queries/getCitationDraft.js, static/src/js/operations/queries/getCollection.js, static/src/js/operations/queries/getVisualization.js
Final step. Should do this after all other tickets are complete. Update the
metadata-preview package to account for all new changes and integrate that onto MMT
Bump edsc/cmr-preview to version 1.5.1
Update MetadataPreview
Update getCitation and getCitationDraft to enable breadcrumbs
MetadataPreview
package.json
graphql queries
- **Environment for testing: Any
- **Collection to test with: Any
1. Select a published citation and ensure the information presented in the preview is accurate and not missing fields
2. Do the same for drafts
Published
Draft
CollectionPreview Update
=> MMT-4059: Update cmr-metadata-preview to latest package and integrate those citations previews to MMT

package-lock.json, serverless/src/createTemplate/handler.js, static/src/js/components/ErrorPageNotFound/ErrorPageNotFound.jsx, static/src/js/components/ErrorPageNotFound/__tests__/ErrorPageNotFound.test.jsx, static/src/js/components/MetadataForm/MetadataForm.jsx, static/src/js/components/PublishPreview/PublishPreview.jsx, static/src/js/components/TemplateForm/TemplateForm.jsx, static/src/js/components/TemplatePreview/TemplatePreview.jsx, static/src/js/pages/DraftListPage/DraftListPage.jsx, test-setup.js, vite.config.js
Use only one uuid function in the application. In the vite config we should only use the polyfills that we actually need.
Replace crypto call to get uuid by using uuid v4. Update vite config.
Where uuid is generated.
=> MMT-4087: Replace crypto call to get uuid by using uuid v4
